{{- if and .Values.ingress.enabled .Values.api.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "flexprice.fullname" . }}-api
  labels:
    {{- include "flexprice.componentLabels" (dict "ctx" . "component" "api") | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "flexprice.fullname" $ }}-api
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
---
{{- if and .Values.frontendIngress.enabled .Values.frontend.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "flexprice.fullname" . }}-frontend
  labels:
    {{- include "flexprice.componentLabels" (dict "ctx" . "component" "frontend") | nindent 4 }}
  {{- with .Values.frontendIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.frontendIngress.className }}
  ingressClassName: {{ .Values.frontendIngress.className }}
  {{- end }}
  {{- if .Values.frontendIngress.tls }}
  tls:
    {{- range .Values.frontendIngress.tls }}
    - hosts:
        - {{ $.Values.frontendIngress.host | quote }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.frontendIngress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "flexprice.fullname" . }}-frontend
                port:
                  number: 3000
{{- end }}
