{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flexprice.fullname" . }}-api
  labels:
    {{- include "flexprice.componentLabels" (dict "ctx" . "component" "api") | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "flexprice.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
{{- end }}

