workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    flexprice-api:
        inputs:
            - location: ./docs/swagger/swagger-3-0.json
        overlays:
            - location: .speakeasy/overlays.yaml
targets:
    flexprice-go:
        target: go
        source: flexprice-api
        output: ./api/go
        publish:
            github:
                owner: flexprice
                repo: go-sdk-temp
        codeSamples:
            output: .speakeasy/code-samples-go.yaml
            labelOverride:
                fixedValue: Go (SDK)
            blocking: false
    flexprice-python:
        target: python
        source: flexprice-api
        output: ./api/python
        publish:
            pypi:
                packageName: flexprice-sdk-test
                token: $PYPI_TOKEN
        codeSamples:
            output: .speakeasy/code-samples-python.yaml
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
    flexprice-typescript:
        target: typescript
        source: flexprice-api
        output: ./api/javascript
        publish:
            npm:
                packageName: flexprice-sdk-test
                access: public
                token: $NPM_TOKEN
        codeSamples:
            output: .speakeasy/code-samples-typescript.yaml
            labelOverride:
                fixedValue: TypeScript (SDK)
            blocking: false
