// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/addonassociation"
	"github.com/flexprice/flexprice/ent/predicate"
)

// AddonAssociationUpdate is the builder for updating AddonAssociation entities.
type AddonAssociationUpdate struct {
	config
	hooks    []Hook
	mutation *AddonAssociationMutation
}

// Where appends a list predicates to the AddonAssociationUpdate builder.
func (_u *AddonAssociationUpdate) Where(ps ...predicate.AddonAssociation) *AddonAssociationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *AddonAssociationUpdate) SetStatus(v string) *AddonAssociationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AddonAssociationUpdate) SetNillableStatus(v *string) *AddonAssociationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AddonAssociationUpdate) SetUpdatedAt(v time.Time) *AddonAssociationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *AddonAssociationUpdate) SetUpdatedBy(v string) *AddonAssociationUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *AddonAssociationUpdate) SetNillableUpdatedBy(v *string) *AddonAssociationUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *AddonAssociationUpdate) ClearUpdatedBy() *AddonAssociationUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *AddonAssociationUpdate) SetStartDate(v time.Time) *AddonAssociationUpdate {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *AddonAssociationUpdate) SetNillableStartDate(v *time.Time) *AddonAssociationUpdate {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// ClearStartDate clears the value of the "start_date" field.
func (_u *AddonAssociationUpdate) ClearStartDate() *AddonAssociationUpdate {
	_u.mutation.ClearStartDate()
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *AddonAssociationUpdate) SetEndDate(v time.Time) *AddonAssociationUpdate {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *AddonAssociationUpdate) SetNillableEndDate(v *time.Time) *AddonAssociationUpdate {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// ClearEndDate clears the value of the "end_date" field.
func (_u *AddonAssociationUpdate) ClearEndDate() *AddonAssociationUpdate {
	_u.mutation.ClearEndDate()
	return _u
}

// SetAddonStatus sets the "addon_status" field.
func (_u *AddonAssociationUpdate) SetAddonStatus(v string) *AddonAssociationUpdate {
	_u.mutation.SetAddonStatus(v)
	return _u
}

// SetNillableAddonStatus sets the "addon_status" field if the given value is not nil.
func (_u *AddonAssociationUpdate) SetNillableAddonStatus(v *string) *AddonAssociationUpdate {
	if v != nil {
		_u.SetAddonStatus(*v)
	}
	return _u
}

// SetCancellationReason sets the "cancellation_reason" field.
func (_u *AddonAssociationUpdate) SetCancellationReason(v string) *AddonAssociationUpdate {
	_u.mutation.SetCancellationReason(v)
	return _u
}

// SetNillableCancellationReason sets the "cancellation_reason" field if the given value is not nil.
func (_u *AddonAssociationUpdate) SetNillableCancellationReason(v *string) *AddonAssociationUpdate {
	if v != nil {
		_u.SetCancellationReason(*v)
	}
	return _u
}

// ClearCancellationReason clears the value of the "cancellation_reason" field.
func (_u *AddonAssociationUpdate) ClearCancellationReason() *AddonAssociationUpdate {
	_u.mutation.ClearCancellationReason()
	return _u
}

// SetCancelledAt sets the "cancelled_at" field.
func (_u *AddonAssociationUpdate) SetCancelledAt(v time.Time) *AddonAssociationUpdate {
	_u.mutation.SetCancelledAt(v)
	return _u
}

// SetNillableCancelledAt sets the "cancelled_at" field if the given value is not nil.
func (_u *AddonAssociationUpdate) SetNillableCancelledAt(v *time.Time) *AddonAssociationUpdate {
	if v != nil {
		_u.SetCancelledAt(*v)
	}
	return _u
}

// ClearCancelledAt clears the value of the "cancelled_at" field.
func (_u *AddonAssociationUpdate) ClearCancelledAt() *AddonAssociationUpdate {
	_u.mutation.ClearCancelledAt()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *AddonAssociationUpdate) SetMetadata(v map[string]interface{}) *AddonAssociationUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *AddonAssociationUpdate) ClearMetadata() *AddonAssociationUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// Mutation returns the AddonAssociationMutation object of the builder.
func (_u *AddonAssociationUpdate) Mutation() *AddonAssociationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AddonAssociationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AddonAssociationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AddonAssociationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AddonAssociationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AddonAssociationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := addonassociation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AddonAssociationUpdate) check() error {
	if v, ok := _u.mutation.AddonStatus(); ok {
		if err := addonassociation.AddonStatusValidator(v); err != nil {
			return &ValidationError{Name: "addon_status", err: fmt.Errorf(`ent: validator failed for field "AddonAssociation.addon_status": %w`, err)}
		}
	}
	return nil
}

func (_u *AddonAssociationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(addonassociation.Table, addonassociation.Columns, sqlgraph.NewFieldSpec(addonassociation.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(addonassociation.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(addonassociation.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(addonassociation.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(addonassociation.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(addonassociation.FieldUpdatedBy, field.TypeString)
	}
	if _u.mutation.EnvironmentIDCleared() {
		_spec.ClearField(addonassociation.FieldEnvironmentID, field.TypeString)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(addonassociation.FieldStartDate, field.TypeTime, value)
	}
	if _u.mutation.StartDateCleared() {
		_spec.ClearField(addonassociation.FieldStartDate, field.TypeTime)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(addonassociation.FieldEndDate, field.TypeTime, value)
	}
	if _u.mutation.EndDateCleared() {
		_spec.ClearField(addonassociation.FieldEndDate, field.TypeTime)
	}
	if value, ok := _u.mutation.AddonStatus(); ok {
		_spec.SetField(addonassociation.FieldAddonStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CancellationReason(); ok {
		_spec.SetField(addonassociation.FieldCancellationReason, field.TypeString, value)
	}
	if _u.mutation.CancellationReasonCleared() {
		_spec.ClearField(addonassociation.FieldCancellationReason, field.TypeString)
	}
	if value, ok := _u.mutation.CancelledAt(); ok {
		_spec.SetField(addonassociation.FieldCancelledAt, field.TypeTime, value)
	}
	if _u.mutation.CancelledAtCleared() {
		_spec.ClearField(addonassociation.FieldCancelledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(addonassociation.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(addonassociation.FieldMetadata, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{addonassociation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AddonAssociationUpdateOne is the builder for updating a single AddonAssociation entity.
type AddonAssociationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AddonAssociationMutation
}

// SetStatus sets the "status" field.
func (_u *AddonAssociationUpdateOne) SetStatus(v string) *AddonAssociationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AddonAssociationUpdateOne) SetNillableStatus(v *string) *AddonAssociationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AddonAssociationUpdateOne) SetUpdatedAt(v time.Time) *AddonAssociationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *AddonAssociationUpdateOne) SetUpdatedBy(v string) *AddonAssociationUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *AddonAssociationUpdateOne) SetNillableUpdatedBy(v *string) *AddonAssociationUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *AddonAssociationUpdateOne) ClearUpdatedBy() *AddonAssociationUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *AddonAssociationUpdateOne) SetStartDate(v time.Time) *AddonAssociationUpdateOne {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *AddonAssociationUpdateOne) SetNillableStartDate(v *time.Time) *AddonAssociationUpdateOne {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// ClearStartDate clears the value of the "start_date" field.
func (_u *AddonAssociationUpdateOne) ClearStartDate() *AddonAssociationUpdateOne {
	_u.mutation.ClearStartDate()
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *AddonAssociationUpdateOne) SetEndDate(v time.Time) *AddonAssociationUpdateOne {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *AddonAssociationUpdateOne) SetNillableEndDate(v *time.Time) *AddonAssociationUpdateOne {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// ClearEndDate clears the value of the "end_date" field.
func (_u *AddonAssociationUpdateOne) ClearEndDate() *AddonAssociationUpdateOne {
	_u.mutation.ClearEndDate()
	return _u
}

// SetAddonStatus sets the "addon_status" field.
func (_u *AddonAssociationUpdateOne) SetAddonStatus(v string) *AddonAssociationUpdateOne {
	_u.mutation.SetAddonStatus(v)
	return _u
}

// SetNillableAddonStatus sets the "addon_status" field if the given value is not nil.
func (_u *AddonAssociationUpdateOne) SetNillableAddonStatus(v *string) *AddonAssociationUpdateOne {
	if v != nil {
		_u.SetAddonStatus(*v)
	}
	return _u
}

// SetCancellationReason sets the "cancellation_reason" field.
func (_u *AddonAssociationUpdateOne) SetCancellationReason(v string) *AddonAssociationUpdateOne {
	_u.mutation.SetCancellationReason(v)
	return _u
}

// SetNillableCancellationReason sets the "cancellation_reason" field if the given value is not nil.
func (_u *AddonAssociationUpdateOne) SetNillableCancellationReason(v *string) *AddonAssociationUpdateOne {
	if v != nil {
		_u.SetCancellationReason(*v)
	}
	return _u
}

// ClearCancellationReason clears the value of the "cancellation_reason" field.
func (_u *AddonAssociationUpdateOne) ClearCancellationReason() *AddonAssociationUpdateOne {
	_u.mutation.ClearCancellationReason()
	return _u
}

// SetCancelledAt sets the "cancelled_at" field.
func (_u *AddonAssociationUpdateOne) SetCancelledAt(v time.Time) *AddonAssociationUpdateOne {
	_u.mutation.SetCancelledAt(v)
	return _u
}

// SetNillableCancelledAt sets the "cancelled_at" field if the given value is not nil.
func (_u *AddonAssociationUpdateOne) SetNillableCancelledAt(v *time.Time) *AddonAssociationUpdateOne {
	if v != nil {
		_u.SetCancelledAt(*v)
	}
	return _u
}

// ClearCancelledAt clears the value of the "cancelled_at" field.
func (_u *AddonAssociationUpdateOne) ClearCancelledAt() *AddonAssociationUpdateOne {
	_u.mutation.ClearCancelledAt()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *AddonAssociationUpdateOne) SetMetadata(v map[string]interface{}) *AddonAssociationUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *AddonAssociationUpdateOne) ClearMetadata() *AddonAssociationUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// Mutation returns the AddonAssociationMutation object of the builder.
func (_u *AddonAssociationUpdateOne) Mutation() *AddonAssociationMutation {
	return _u.mutation
}

// Where appends a list predicates to the AddonAssociationUpdate builder.
func (_u *AddonAssociationUpdateOne) Where(ps ...predicate.AddonAssociation) *AddonAssociationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AddonAssociationUpdateOne) Select(field string, fields ...string) *AddonAssociationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AddonAssociation entity.
func (_u *AddonAssociationUpdateOne) Save(ctx context.Context) (*AddonAssociation, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AddonAssociationUpdateOne) SaveX(ctx context.Context) *AddonAssociation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AddonAssociationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AddonAssociationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AddonAssociationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := addonassociation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AddonAssociationUpdateOne) check() error {
	if v, ok := _u.mutation.AddonStatus(); ok {
		if err := addonassociation.AddonStatusValidator(v); err != nil {
			return &ValidationError{Name: "addon_status", err: fmt.Errorf(`ent: validator failed for field "AddonAssociation.addon_status": %w`, err)}
		}
	}
	return nil
}

func (_u *AddonAssociationUpdateOne) sqlSave(ctx context.Context) (_node *AddonAssociation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(addonassociation.Table, addonassociation.Columns, sqlgraph.NewFieldSpec(addonassociation.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AddonAssociation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, addonassociation.FieldID)
		for _, f := range fields {
			if !addonassociation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != addonassociation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(addonassociation.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(addonassociation.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(addonassociation.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(addonassociation.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(addonassociation.FieldUpdatedBy, field.TypeString)
	}
	if _u.mutation.EnvironmentIDCleared() {
		_spec.ClearField(addonassociation.FieldEnvironmentID, field.TypeString)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(addonassociation.FieldStartDate, field.TypeTime, value)
	}
	if _u.mutation.StartDateCleared() {
		_spec.ClearField(addonassociation.FieldStartDate, field.TypeTime)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(addonassociation.FieldEndDate, field.TypeTime, value)
	}
	if _u.mutation.EndDateCleared() {
		_spec.ClearField(addonassociation.FieldEndDate, field.TypeTime)
	}
	if value, ok := _u.mutation.AddonStatus(); ok {
		_spec.SetField(addonassociation.FieldAddonStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CancellationReason(); ok {
		_spec.SetField(addonassociation.FieldCancellationReason, field.TypeString, value)
	}
	if _u.mutation.CancellationReasonCleared() {
		_spec.ClearField(addonassociation.FieldCancellationReason, field.TypeString)
	}
	if value, ok := _u.mutation.CancelledAt(); ok {
		_spec.SetField(addonassociation.FieldCancelledAt, field.TypeTime, value)
	}
	if _u.mutation.CancelledAtCleared() {
		_spec.ClearField(addonassociation.FieldCancelledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(addonassociation.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(addonassociation.FieldMetadata, field.TypeJSON)
	}
	_node = &AddonAssociation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{addonassociation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
