// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/flexprice/flexprice/ent/alertsettings"
	"github.com/flexprice/flexprice/internal/types"
)

// AlertSettings is the model entity for the AlertSettings schema.
type AlertSettings struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID string `json:"tenant_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy string `json:"created_by,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy string `json:"updated_by,omitempty"`
	// EnvironmentID holds the value of the "environment_id" field.
	EnvironmentID string `json:"environment_id,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// EntityType holds the value of the "entity_type" field.
	EntityType types.AlertEntityType `json:"entity_type,omitempty"`
	// EntityID holds the value of the "entity_id" field.
	EntityID string `json:"entity_id,omitempty"`
	// ParentEntityType holds the value of the "parent_entity_type" field.
	ParentEntityType *types.AlertEntityType `json:"parent_entity_type,omitempty"`
	// ParentEntityID holds the value of the "parent_entity_id" field.
	ParentEntityID *string `json:"parent_entity_id,omitempty"`
	// Config holds the value of the "config" field.
	Config       types.AlertSettings `json:"config,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AlertSettings) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case alertsettings.FieldConfig:
			values[i] = new([]byte)
		case alertsettings.FieldEnabled:
			values[i] = new(sql.NullBool)
		case alertsettings.FieldID, alertsettings.FieldTenantID, alertsettings.FieldStatus, alertsettings.FieldCreatedBy, alertsettings.FieldUpdatedBy, alertsettings.FieldEnvironmentID, alertsettings.FieldEntityType, alertsettings.FieldEntityID, alertsettings.FieldParentEntityType, alertsettings.FieldParentEntityID:
			values[i] = new(sql.NullString)
		case alertsettings.FieldCreatedAt, alertsettings.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AlertSettings fields.
func (as *AlertSettings) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case alertsettings.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				as.ID = value.String
			}
		case alertsettings.FieldTenantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				as.TenantID = value.String
			}
		case alertsettings.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				as.Status = value.String
			}
		case alertsettings.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				as.CreatedAt = value.Time
			}
		case alertsettings.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				as.UpdatedAt = value.Time
			}
		case alertsettings.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				as.CreatedBy = value.String
			}
		case alertsettings.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				as.UpdatedBy = value.String
			}
		case alertsettings.FieldEnvironmentID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field environment_id", values[i])
			} else if value.Valid {
				as.EnvironmentID = value.String
			}
		case alertsettings.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				as.Enabled = value.Bool
			}
		case alertsettings.FieldEntityType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field entity_type", values[i])
			} else if value.Valid {
				as.EntityType = types.AlertEntityType(value.String)
			}
		case alertsettings.FieldEntityID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field entity_id", values[i])
			} else if value.Valid {
				as.EntityID = value.String
			}
		case alertsettings.FieldParentEntityType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field parent_entity_type", values[i])
			} else if value.Valid {
				as.ParentEntityType = new(types.AlertEntityType)
				*as.ParentEntityType = types.AlertEntityType(value.String)
			}
		case alertsettings.FieldParentEntityID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field parent_entity_id", values[i])
			} else if value.Valid {
				as.ParentEntityID = new(string)
				*as.ParentEntityID = value.String
			}
		case alertsettings.FieldConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field config", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &as.Config); err != nil {
					return fmt.Errorf("unmarshal field config: %w", err)
				}
			}
		default:
			as.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AlertSettings.
// This includes values selected through modifiers, order, etc.
func (as *AlertSettings) Value(name string) (ent.Value, error) {
	return as.selectValues.Get(name)
}

// Update returns a builder for updating this AlertSettings.
// Note that you need to call AlertSettings.Unwrap() before calling this method if this AlertSettings
// was returned from a transaction, and the transaction was committed or rolled back.
func (as *AlertSettings) Update() *AlertSettingsUpdateOne {
	return NewAlertSettingsClient(as.config).UpdateOne(as)
}

// Unwrap unwraps the AlertSettings entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (as *AlertSettings) Unwrap() *AlertSettings {
	_tx, ok := as.config.driver.(*txDriver)
	if !ok {
		panic("ent: AlertSettings is not a transactional entity")
	}
	as.config.driver = _tx.drv
	return as
}

// String implements the fmt.Stringer.
func (as *AlertSettings) String() string {
	var builder strings.Builder
	builder.WriteString("AlertSettings(")
	builder.WriteString(fmt.Sprintf("id=%v, ", as.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(as.TenantID)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(as.Status)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(as.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(as.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(as.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(as.UpdatedBy)
	builder.WriteString(", ")
	builder.WriteString("environment_id=")
	builder.WriteString(as.EnvironmentID)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", as.Enabled))
	builder.WriteString(", ")
	builder.WriteString("entity_type=")
	builder.WriteString(fmt.Sprintf("%v", as.EntityType))
	builder.WriteString(", ")
	builder.WriteString("entity_id=")
	builder.WriteString(as.EntityID)
	builder.WriteString(", ")
	if v := as.ParentEntityType; v != nil {
		builder.WriteString("parent_entity_type=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := as.ParentEntityID; v != nil {
		builder.WriteString("parent_entity_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("config=")
	builder.WriteString(fmt.Sprintf("%v", as.Config))
	builder.WriteByte(')')
	return builder.String()
}

// AlertSettingsSlice is a parsable slice of AlertSettings.
type AlertSettingsSlice []*AlertSettings
