// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/alertsettings"
	"github.com/flexprice/flexprice/ent/predicate"
	"github.com/flexprice/flexprice/internal/types"
)

// AlertSettingsUpdate is the builder for updating AlertSettings entities.
type AlertSettingsUpdate struct {
	config
	hooks    []Hook
	mutation *AlertSettingsMutation
}

// Where appends a list predicates to the AlertSettingsUpdate builder.
func (_u *AlertSettingsUpdate) Where(ps ...predicate.AlertSettings) *AlertSettingsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *AlertSettingsUpdate) SetStatus(v string) *AlertSettingsUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AlertSettingsUpdate) SetNillableStatus(v *string) *AlertSettingsUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AlertSettingsUpdate) SetUpdatedAt(v time.Time) *AlertSettingsUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *AlertSettingsUpdate) SetUpdatedBy(v string) *AlertSettingsUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *AlertSettingsUpdate) SetNillableUpdatedBy(v *string) *AlertSettingsUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *AlertSettingsUpdate) ClearUpdatedBy() *AlertSettingsUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *AlertSettingsUpdate) SetEnabled(v bool) *AlertSettingsUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *AlertSettingsUpdate) SetNillableEnabled(v *bool) *AlertSettingsUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *AlertSettingsUpdate) SetConfig(v types.AlertSettings) *AlertSettingsUpdate {
	_u.mutation.SetConfig(v)
	return _u
}

// SetNillableConfig sets the "config" field if the given value is not nil.
func (_u *AlertSettingsUpdate) SetNillableConfig(v *types.AlertSettings) *AlertSettingsUpdate {
	if v != nil {
		_u.SetConfig(*v)
	}
	return _u
}

// Mutation returns the AlertSettingsMutation object of the builder.
func (_u *AlertSettingsUpdate) Mutation() *AlertSettingsMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AlertSettingsUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AlertSettingsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AlertSettingsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AlertSettingsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AlertSettingsUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := alertsettings.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *AlertSettingsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(alertsettings.Table, alertsettings.Columns, sqlgraph.NewFieldSpec(alertsettings.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(alertsettings.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(alertsettings.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(alertsettings.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(alertsettings.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(alertsettings.FieldUpdatedBy, field.TypeString)
	}
	if _u.mutation.EnvironmentIDCleared() {
		_spec.ClearField(alertsettings.FieldEnvironmentID, field.TypeString)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(alertsettings.FieldEnabled, field.TypeBool, value)
	}
	if _u.mutation.ParentEntityTypeCleared() {
		_spec.ClearField(alertsettings.FieldParentEntityType, field.TypeEnum)
	}
	if _u.mutation.ParentEntityIDCleared() {
		_spec.ClearField(alertsettings.FieldParentEntityID, field.TypeString)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(alertsettings.FieldConfig, field.TypeJSON, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{alertsettings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AlertSettingsUpdateOne is the builder for updating a single AlertSettings entity.
type AlertSettingsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AlertSettingsMutation
}

// SetStatus sets the "status" field.
func (_u *AlertSettingsUpdateOne) SetStatus(v string) *AlertSettingsUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AlertSettingsUpdateOne) SetNillableStatus(v *string) *AlertSettingsUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AlertSettingsUpdateOne) SetUpdatedAt(v time.Time) *AlertSettingsUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *AlertSettingsUpdateOne) SetUpdatedBy(v string) *AlertSettingsUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *AlertSettingsUpdateOne) SetNillableUpdatedBy(v *string) *AlertSettingsUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *AlertSettingsUpdateOne) ClearUpdatedBy() *AlertSettingsUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *AlertSettingsUpdateOne) SetEnabled(v bool) *AlertSettingsUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *AlertSettingsUpdateOne) SetNillableEnabled(v *bool) *AlertSettingsUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *AlertSettingsUpdateOne) SetConfig(v types.AlertSettings) *AlertSettingsUpdateOne {
	_u.mutation.SetConfig(v)
	return _u
}

// SetNillableConfig sets the "config" field if the given value is not nil.
func (_u *AlertSettingsUpdateOne) SetNillableConfig(v *types.AlertSettings) *AlertSettingsUpdateOne {
	if v != nil {
		_u.SetConfig(*v)
	}
	return _u
}

// Mutation returns the AlertSettingsMutation object of the builder.
func (_u *AlertSettingsUpdateOne) Mutation() *AlertSettingsMutation {
	return _u.mutation
}

// Where appends a list predicates to the AlertSettingsUpdate builder.
func (_u *AlertSettingsUpdateOne) Where(ps ...predicate.AlertSettings) *AlertSettingsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AlertSettingsUpdateOne) Select(field string, fields ...string) *AlertSettingsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AlertSettings entity.
func (_u *AlertSettingsUpdateOne) Save(ctx context.Context) (*AlertSettings, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AlertSettingsUpdateOne) SaveX(ctx context.Context) *AlertSettings {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AlertSettingsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AlertSettingsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AlertSettingsUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := alertsettings.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *AlertSettingsUpdateOne) sqlSave(ctx context.Context) (_node *AlertSettings, err error) {
	_spec := sqlgraph.NewUpdateSpec(alertsettings.Table, alertsettings.Columns, sqlgraph.NewFieldSpec(alertsettings.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AlertSettings.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, alertsettings.FieldID)
		for _, f := range fields {
			if !alertsettings.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != alertsettings.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(alertsettings.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(alertsettings.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(alertsettings.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(alertsettings.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(alertsettings.FieldUpdatedBy, field.TypeString)
	}
	if _u.mutation.EnvironmentIDCleared() {
		_spec.ClearField(alertsettings.FieldEnvironmentID, field.TypeString)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(alertsettings.FieldEnabled, field.TypeBool, value)
	}
	if _u.mutation.ParentEntityTypeCleared() {
		_spec.ClearField(alertsettings.FieldParentEntityType, field.TypeEnum)
	}
	if _u.mutation.ParentEntityIDCleared() {
		_spec.ClearField(alertsettings.FieldParentEntityID, field.TypeString)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(alertsettings.FieldConfig, field.TypeJSON, value)
	}
	_node = &AlertSettings{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{alertsettings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
