// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/analyticssavedview"
	"github.com/flexprice/flexprice/ent/predicate"
)

// AnalyticsSavedViewUpdate is the builder for updating AnalyticsSavedView entities.
type AnalyticsSavedViewUpdate struct {
	config
	hooks    []Hook
	mutation *AnalyticsSavedViewMutation
}

// Where appends a list predicates to the AnalyticsSavedViewUpdate builder.
func (asvu *AnalyticsSavedViewUpdate) Where(ps ...predicate.AnalyticsSavedView) *AnalyticsSavedViewUpdate {
	asvu.mutation.Where(ps...)
	return asvu
}

// SetStatus sets the "status" field.
func (asvu *AnalyticsSavedViewUpdate) SetStatus(s string) *AnalyticsSavedViewUpdate {
	asvu.mutation.SetStatus(s)
	return asvu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (asvu *AnalyticsSavedViewUpdate) SetNillableStatus(s *string) *AnalyticsSavedViewUpdate {
	if s != nil {
		asvu.SetStatus(*s)
	}
	return asvu
}

// SetUpdatedAt sets the "updated_at" field.
func (asvu *AnalyticsSavedViewUpdate) SetUpdatedAt(t time.Time) *AnalyticsSavedViewUpdate {
	asvu.mutation.SetUpdatedAt(t)
	return asvu
}

// SetUpdatedBy sets the "updated_by" field.
func (asvu *AnalyticsSavedViewUpdate) SetUpdatedBy(s string) *AnalyticsSavedViewUpdate {
	asvu.mutation.SetUpdatedBy(s)
	return asvu
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (asvu *AnalyticsSavedViewUpdate) SetNillableUpdatedBy(s *string) *AnalyticsSavedViewUpdate {
	if s != nil {
		asvu.SetUpdatedBy(*s)
	}
	return asvu
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (asvu *AnalyticsSavedViewUpdate) ClearUpdatedBy() *AnalyticsSavedViewUpdate {
	asvu.mutation.ClearUpdatedBy()
	return asvu
}

// SetName sets the "name" field.
func (asvu *AnalyticsSavedViewUpdate) SetName(s string) *AnalyticsSavedViewUpdate {
	asvu.mutation.SetName(s)
	return asvu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (asvu *AnalyticsSavedViewUpdate) SetNillableName(s *string) *AnalyticsSavedViewUpdate {
	if s != nil {
		asvu.SetName(*s)
	}
	return asvu
}

// SetVersion sets the "version" field.
func (asvu *AnalyticsSavedViewUpdate) SetVersion(i int) *AnalyticsSavedViewUpdate {
	asvu.mutation.ResetVersion()
	asvu.mutation.SetVersion(i)
	return asvu
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (asvu *AnalyticsSavedViewUpdate) SetNillableVersion(i *int) *AnalyticsSavedViewUpdate {
	if i != nil {
		asvu.SetVersion(*i)
	}
	return asvu
}

// AddVersion adds i to the "version" field.
func (asvu *AnalyticsSavedViewUpdate) AddVersion(i int) *AnalyticsSavedViewUpdate {
	asvu.mutation.AddVersion(i)
	return asvu
}

// SetDefinition sets the "definition" field.
func (asvu *AnalyticsSavedViewUpdate) SetDefinition(m map[string]interface{}) *AnalyticsSavedViewUpdate {
	asvu.mutation.SetDefinition(m)
	return asvu
}

// Mutation returns the AnalyticsSavedViewMutation object of the builder.
func (asvu *AnalyticsSavedViewUpdate) Mutation() *AnalyticsSavedViewMutation {
	return asvu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (asvu *AnalyticsSavedViewUpdate) Save(ctx context.Context) (int, error) {
	asvu.defaults()
	return withHooks(ctx, asvu.sqlSave, asvu.mutation, asvu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (asvu *AnalyticsSavedViewUpdate) SaveX(ctx context.Context) int {
	affected, err := asvu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (asvu *AnalyticsSavedViewUpdate) Exec(ctx context.Context) error {
	_, err := asvu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (asvu *AnalyticsSavedViewUpdate) ExecX(ctx context.Context) {
	if err := asvu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (asvu *AnalyticsSavedViewUpdate) defaults() {
	if _, ok := asvu.mutation.UpdatedAt(); !ok {
		v := analyticssavedview.UpdateDefaultUpdatedAt()
		asvu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (asvu *AnalyticsSavedViewUpdate) check() error {
	if v, ok := asvu.mutation.Name(); ok {
		if err := analyticssavedview.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AnalyticsSavedView.name": %w`, err)}
		}
	}
	return nil
}

func (asvu *AnalyticsSavedViewUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := asvu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(analyticssavedview.Table, analyticssavedview.Columns, sqlgraph.NewFieldSpec(analyticssavedview.FieldID, field.TypeString))
	if ps := asvu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := asvu.mutation.Status(); ok {
		_spec.SetField(analyticssavedview.FieldStatus, field.TypeString, value)
	}
	if value, ok := asvu.mutation.UpdatedAt(); ok {
		_spec.SetField(analyticssavedview.FieldUpdatedAt, field.TypeTime, value)
	}
	if asvu.mutation.CreatedByCleared() {
		_spec.ClearField(analyticssavedview.FieldCreatedBy, field.TypeString)
	}
	if value, ok := asvu.mutation.UpdatedBy(); ok {
		_spec.SetField(analyticssavedview.FieldUpdatedBy, field.TypeString, value)
	}
	if asvu.mutation.UpdatedByCleared() {
		_spec.ClearField(analyticssavedview.FieldUpdatedBy, field.TypeString)
	}
	if asvu.mutation.EnvironmentIDCleared() {
		_spec.ClearField(analyticssavedview.FieldEnvironmentID, field.TypeString)
	}
	if value, ok := asvu.mutation.Name(); ok {
		_spec.SetField(analyticssavedview.FieldName, field.TypeString, value)
	}
	if value, ok := asvu.mutation.Version(); ok {
		_spec.SetField(analyticssavedview.FieldVersion, field.TypeInt, value)
	}
	if value, ok := asvu.mutation.AddedVersion(); ok {
		_spec.AddField(analyticssavedview.FieldVersion, field.TypeInt, value)
	}
	if value, ok := asvu.mutation.Definition(); ok {
		_spec.SetField(analyticssavedview.FieldDefinition, field.TypeJSON, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, asvu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{analyticssavedview.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	asvu.mutation.done = true
	return n, nil
}

// AnalyticsSavedViewUpdateOne is the builder for updating a single AnalyticsSavedView entity.
type AnalyticsSavedViewUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AnalyticsSavedViewMutation
}

// SetStatus sets the "status" field.
func (asvuo *AnalyticsSavedViewUpdateOne) SetStatus(s string) *AnalyticsSavedViewUpdateOne {
	asvuo.mutation.SetStatus(s)
	return asvuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (asvuo *AnalyticsSavedViewUpdateOne) SetNillableStatus(s *string) *AnalyticsSavedViewUpdateOne {
	if s != nil {
		asvuo.SetStatus(*s)
	}
	return asvuo
}

// SetUpdatedAt sets the "updated_at" field.
func (asvuo *AnalyticsSavedViewUpdateOne) SetUpdatedAt(t time.Time) *AnalyticsSavedViewUpdateOne {
	asvuo.mutation.SetUpdatedAt(t)
	return asvuo
}

// SetUpdatedBy sets the "updated_by" field.
func (asvuo *AnalyticsSavedViewUpdateOne) SetUpdatedBy(s string) *AnalyticsSavedViewUpdateOne {
	asvuo.mutation.SetUpdatedBy(s)
	return asvuo
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (asvuo *AnalyticsSavedViewUpdateOne) SetNillableUpdatedBy(s *string) *AnalyticsSavedViewUpdateOne {
	if s != nil {
		asvuo.SetUpdatedBy(*s)
	}
	return asvuo
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (asvuo *AnalyticsSavedViewUpdateOne) ClearUpdatedBy() *AnalyticsSavedViewUpdateOne {
	asvuo.mutation.ClearUpdatedBy()
	return asvuo
}

// SetName sets the "name" field.
func (asvuo *AnalyticsSavedViewUpdateOne) SetName(s string) *AnalyticsSavedViewUpdateOne {
	asvuo.mutation.SetName(s)
	return asvuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (asvuo *AnalyticsSavedViewUpdateOne) SetNillableName(s *string) *AnalyticsSavedViewUpdateOne {
	if s != nil {
		asvuo.SetName(*s)
	}
	return asvuo
}

// SetVersion sets the "version" field.
func (asvuo *AnalyticsSavedViewUpdateOne) SetVersion(i int) *AnalyticsSavedViewUpdateOne {
	asvuo.mutation.ResetVersion()
	asvuo.mutation.SetVersion(i)
	return asvuo
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (asvuo *AnalyticsSavedViewUpdateOne) SetNillableVersion(i *int) *AnalyticsSavedViewUpdateOne {
	if i != nil {
		asvuo.SetVersion(*i)
	}
	return asvuo
}

// AddVersion adds i to the "version" field.
func (asvuo *AnalyticsSavedViewUpdateOne) AddVersion(i int) *AnalyticsSavedViewUpdateOne {
	asvuo.mutation.AddVersion(i)
	return asvuo
}

// SetDefinition sets the "definition" field.
func (asvuo *AnalyticsSavedViewUpdateOne) SetDefinition(m map[string]interface{}) *AnalyticsSavedViewUpdateOne {
	asvuo.mutation.SetDefinition(m)
	return asvuo
}

// Mutation returns the AnalyticsSavedViewMutation object of the builder.
func (asvuo *AnalyticsSavedViewUpdateOne) Mutation() *AnalyticsSavedViewMutation {
	return asvuo.mutation
}

// Where appends a list predicates to the AnalyticsSavedViewUpdate builder.
func (asvuo *AnalyticsSavedViewUpdateOne) Where(ps ...predicate.AnalyticsSavedView) *AnalyticsSavedViewUpdateOne {
	asvuo.mutation.Where(ps...)
	return asvuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (asvuo *AnalyticsSavedViewUpdateOne) Select(field string, fields ...string) *AnalyticsSavedViewUpdateOne {
	asvuo.fields = append([]string{field}, fields...)
	return asvuo
}

// Save executes the query and returns the updated AnalyticsSavedView entity.
func (asvuo *AnalyticsSavedViewUpdateOne) Save(ctx context.Context) (*AnalyticsSavedView, error) {
	asvuo.defaults()
	return withHooks(ctx, asvuo.sqlSave, asvuo.mutation, asvuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (asvuo *AnalyticsSavedViewUpdateOne) SaveX(ctx context.Context) *AnalyticsSavedView {
	node, err := asvuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (asvuo *AnalyticsSavedViewUpdateOne) Exec(ctx context.Context) error {
	_, err := asvuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (asvuo *AnalyticsSavedViewUpdateOne) ExecX(ctx context.Context) {
	if err := asvuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (asvuo *AnalyticsSavedViewUpdateOne) defaults() {
	if _, ok := asvuo.mutation.UpdatedAt(); !ok {
		v := analyticssavedview.UpdateDefaultUpdatedAt()
		asvuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (asvuo *AnalyticsSavedViewUpdateOne) check() error {
	if v, ok := asvuo.mutation.Name(); ok {
		if err := analyticssavedview.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AnalyticsSavedView.name": %w`, err)}
		}
	}
	return nil
}

func (asvuo *AnalyticsSavedViewUpdateOne) sqlSave(ctx context.Context) (_node *AnalyticsSavedView, err error) {
	if err := asvuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(analyticssavedview.Table, analyticssavedview.Columns, sqlgraph.NewFieldSpec(analyticssavedview.FieldID, field.TypeString))
	id, ok := asvuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AnalyticsSavedView.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := asvuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, analyticssavedview.FieldID)
		for _, f := range fields {
			if !analyticssavedview.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != analyticssavedview.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := asvuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := asvuo.mutation.Status(); ok {
		_spec.SetField(analyticssavedview.FieldStatus, field.TypeString, value)
	}
	if value, ok := asvuo.mutation.UpdatedAt(); ok {
		_spec.SetField(analyticssavedview.FieldUpdatedAt, field.TypeTime, value)
	}
	if asvuo.mutation.CreatedByCleared() {
		_spec.ClearField(analyticssavedview.FieldCreatedBy, field.TypeString)
	}
	if value, ok := asvuo.mutation.UpdatedBy(); ok {
		_spec.SetField(analyticssavedview.FieldUpdatedBy, field.TypeString, value)
	}
	if asvuo.mutation.UpdatedByCleared() {
		_spec.ClearField(analyticssavedview.FieldUpdatedBy, field.TypeString)
	}
	if asvuo.mutation.EnvironmentIDCleared() {
		_spec.ClearField(analyticssavedview.FieldEnvironmentID, field.TypeString)
	}
	if value, ok := asvuo.mutation.Name(); ok {
		_spec.SetField(analyticssavedview.FieldName, field.TypeString, value)
	}
	if value, ok := asvuo.mutation.Version(); ok {
		_spec.SetField(analyticssavedview.FieldVersion, field.TypeInt, value)
	}
	if value, ok := asvuo.mutation.AddedVersion(); ok {
		_spec.AddField(analyticssavedview.FieldVersion, field.TypeInt, value)
	}
	if value, ok := asvuo.mutation.Definition(); ok {
		_spec.SetField(analyticssavedview.FieldDefinition, field.TypeJSON, value)
	}
	_node = &AnalyticsSavedView{config: asvuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, asvuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{analyticssavedview.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	asvuo.mutation.done = true
	return _node, nil
}
