// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/flexprice/flexprice/ent/creditgrantapplication"
	"github.com/flexprice/flexprice/internal/types"
	"github.com/shopspring/decimal"
)

// CreditGrantApplication is the model entity for the CreditGrantApplication schema.
type CreditGrantApplication struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID string `json:"tenant_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy string `json:"created_by,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy string `json:"updated_by,omitempty"`
	// EnvironmentID holds the value of the "environment_id" field.
	EnvironmentID string `json:"environment_id,omitempty"`
	// CreditGrantID holds the value of the "credit_grant_id" field.
	CreditGrantID string `json:"credit_grant_id,omitempty"`
	// SubscriptionID holds the value of the "subscription_id" field.
	SubscriptionID string `json:"subscription_id,omitempty"`
	// ScheduledFor holds the value of the "scheduled_for" field.
	ScheduledFor time.Time `json:"scheduled_for,omitempty"`
	// AppliedAt holds the value of the "applied_at" field.
	AppliedAt *time.Time `json:"applied_at,omitempty"`
	// PeriodStart holds the value of the "period_start" field.
	PeriodStart time.Time `json:"period_start,omitempty"`
	// PeriodEnd holds the value of the "period_end" field.
	PeriodEnd *time.Time `json:"period_end,omitempty"`
	// ApplicationStatus holds the value of the "application_status" field.
	ApplicationStatus types.ApplicationStatus `json:"application_status,omitempty"`
	// Credits holds the value of the "credits" field.
	Credits decimal.Decimal `json:"credits,omitempty"`
	// ApplicationReason holds the value of the "application_reason" field.
	ApplicationReason types.CreditGrantApplicationReason `json:"application_reason,omitempty"`
	// SubscriptionStatusAtApplication holds the value of the "subscription_status_at_application" field.
	SubscriptionStatusAtApplication types.SubscriptionStatus `json:"subscription_status_at_application,omitempty"`
	// RetryCount holds the value of the "retry_count" field.
	RetryCount int `json:"retry_count,omitempty"`
	// FailureReason holds the value of the "failure_reason" field.
	FailureReason *string `json:"failure_reason,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata types.Metadata `json:"metadata,omitempty"`
	// IdempotencyKey holds the value of the "idempotency_key" field.
	IdempotencyKey string `json:"idempotency_key,omitempty"`
	selectValues   sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CreditGrantApplication) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case creditgrantapplication.FieldCredits:
			values[i] = new(decimal.Decimal)
		case creditgrantapplication.FieldRetryCount:
			values[i] = new(sql.NullInt64)
		case creditgrantapplication.FieldID, creditgrantapplication.FieldTenantID, creditgrantapplication.FieldStatus, creditgrantapplication.FieldCreatedBy, creditgrantapplication.FieldUpdatedBy, creditgrantapplication.FieldEnvironmentID, creditgrantapplication.FieldCreditGrantID, creditgrantapplication.FieldSubscriptionID, creditgrantapplication.FieldApplicationStatus, creditgrantapplication.FieldApplicationReason, creditgrantapplication.FieldSubscriptionStatusAtApplication, creditgrantapplication.FieldFailureReason, creditgrantapplication.FieldIdempotencyKey:
			values[i] = new(sql.NullString)
		case creditgrantapplication.FieldCreatedAt, creditgrantapplication.FieldUpdatedAt, creditgrantapplication.FieldScheduledFor, creditgrantapplication.FieldAppliedAt, creditgrantapplication.FieldPeriodStart, creditgrantapplication.FieldPeriodEnd:
			values[i] = new(sql.NullTime)
		case creditgrantapplication.FieldMetadata:
			values[i] = new(types.Metadata)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CreditGrantApplication fields.
func (_m *CreditGrantApplication) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case creditgrantapplication.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case creditgrantapplication.FieldTenantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = value.String
			}
		case creditgrantapplication.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case creditgrantapplication.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case creditgrantapplication.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case creditgrantapplication.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.String
			}
		case creditgrantapplication.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = value.String
			}
		case creditgrantapplication.FieldEnvironmentID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field environment_id", values[i])
			} else if value.Valid {
				_m.EnvironmentID = value.String
			}
		case creditgrantapplication.FieldCreditGrantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field credit_grant_id", values[i])
			} else if value.Valid {
				_m.CreditGrantID = value.String
			}
		case creditgrantapplication.FieldSubscriptionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_id", values[i])
			} else if value.Valid {
				_m.SubscriptionID = value.String
			}
		case creditgrantapplication.FieldScheduledFor:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field scheduled_for", values[i])
			} else if value.Valid {
				_m.ScheduledFor = value.Time
			}
		case creditgrantapplication.FieldAppliedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field applied_at", values[i])
			} else if value.Valid {
				_m.AppliedAt = new(time.Time)
				*_m.AppliedAt = value.Time
			}
		case creditgrantapplication.FieldPeriodStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field period_start", values[i])
			} else if value.Valid {
				_m.PeriodStart = value.Time
			}
		case creditgrantapplication.FieldPeriodEnd:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field period_end", values[i])
			} else if value.Valid {
				_m.PeriodEnd = new(time.Time)
				*_m.PeriodEnd = value.Time
			}
		case creditgrantapplication.FieldApplicationStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field application_status", values[i])
			} else if value.Valid {
				_m.ApplicationStatus = types.ApplicationStatus(value.String)
			}
		case creditgrantapplication.FieldCredits:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field credits", values[i])
			} else if value != nil {
				_m.Credits = *value
			}
		case creditgrantapplication.FieldApplicationReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field application_reason", values[i])
			} else if value.Valid {
				_m.ApplicationReason = types.CreditGrantApplicationReason(value.String)
			}
		case creditgrantapplication.FieldSubscriptionStatusAtApplication:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_status_at_application", values[i])
			} else if value.Valid {
				_m.SubscriptionStatusAtApplication = types.SubscriptionStatus(value.String)
			}
		case creditgrantapplication.FieldRetryCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field retry_count", values[i])
			} else if value.Valid {
				_m.RetryCount = int(value.Int64)
			}
		case creditgrantapplication.FieldFailureReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field failure_reason", values[i])
			} else if value.Valid {
				_m.FailureReason = new(string)
				*_m.FailureReason = value.String
			}
		case creditgrantapplication.FieldMetadata:
			if value, ok := values[i].(*types.Metadata); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil {
				_m.Metadata = *value
			}
		case creditgrantapplication.FieldIdempotencyKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key", values[i])
			} else if value.Valid {
				_m.IdempotencyKey = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CreditGrantApplication.
// This includes values selected through modifiers, order, etc.
func (_m *CreditGrantApplication) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CreditGrantApplication.
// Note that you need to call CreditGrantApplication.Unwrap() before calling this method if this CreditGrantApplication
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CreditGrantApplication) Update() *CreditGrantApplicationUpdateOne {
	return NewCreditGrantApplicationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CreditGrantApplication entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CreditGrantApplication) Unwrap() *CreditGrantApplication {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CreditGrantApplication is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CreditGrantApplication) String() string {
	var builder strings.Builder
	builder.WriteString("CreditGrantApplication(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(_m.TenantID)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(_m.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(_m.UpdatedBy)
	builder.WriteString(", ")
	builder.WriteString("environment_id=")
	builder.WriteString(_m.EnvironmentID)
	builder.WriteString(", ")
	builder.WriteString("credit_grant_id=")
	builder.WriteString(_m.CreditGrantID)
	builder.WriteString(", ")
	builder.WriteString("subscription_id=")
	builder.WriteString(_m.SubscriptionID)
	builder.WriteString(", ")
	builder.WriteString("scheduled_for=")
	builder.WriteString(_m.ScheduledFor.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.AppliedAt; v != nil {
		builder.WriteString("applied_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("period_start=")
	builder.WriteString(_m.PeriodStart.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.PeriodEnd; v != nil {
		builder.WriteString("period_end=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("application_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.ApplicationStatus))
	builder.WriteString(", ")
	builder.WriteString("credits=")
	builder.WriteString(fmt.Sprintf("%v", _m.Credits))
	builder.WriteString(", ")
	builder.WriteString("application_reason=")
	builder.WriteString(fmt.Sprintf("%v", _m.ApplicationReason))
	builder.WriteString(", ")
	builder.WriteString("subscription_status_at_application=")
	builder.WriteString(fmt.Sprintf("%v", _m.SubscriptionStatusAtApplication))
	builder.WriteString(", ")
	builder.WriteString("retry_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RetryCount))
	builder.WriteString(", ")
	if v := _m.FailureReason; v != nil {
		builder.WriteString("failure_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("idempotency_key=")
	builder.WriteString(_m.IdempotencyKey)
	builder.WriteByte(')')
	return builder.String()
}

// CreditGrantApplications is a parsable slice of CreditGrantApplication.
type CreditGrantApplications []*CreditGrantApplication
