// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/feature"
	"github.com/flexprice/flexprice/internal/types"
	"github.com/shopspring/decimal"
)

// FeatureCreate is the builder for creating a Feature entity.
type FeatureCreate struct {
	config
	mutation *FeatureMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *FeatureCreate) SetTenantID(v string) *FeatureCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *FeatureCreate) SetStatus(v string) *FeatureCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *FeatureCreate) SetNillableStatus(v *string) *FeatureCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *FeatureCreate) SetCreatedAt(v time.Time) *FeatureCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *FeatureCreate) SetNillableCreatedAt(v *time.Time) *FeatureCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *FeatureCreate) SetUpdatedAt(v time.Time) *FeatureCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *FeatureCreate) SetNillableUpdatedAt(v *time.Time) *FeatureCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *FeatureCreate) SetCreatedBy(v string) *FeatureCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *FeatureCreate) SetNillableCreatedBy(v *string) *FeatureCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *FeatureCreate) SetUpdatedBy(v string) *FeatureCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *FeatureCreate) SetNillableUpdatedBy(v *string) *FeatureCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetEnvironmentID sets the "environment_id" field.
func (_c *FeatureCreate) SetEnvironmentID(v string) *FeatureCreate {
	_c.mutation.SetEnvironmentID(v)
	return _c
}

// SetNillableEnvironmentID sets the "environment_id" field if the given value is not nil.
func (_c *FeatureCreate) SetNillableEnvironmentID(v *string) *FeatureCreate {
	if v != nil {
		_c.SetEnvironmentID(*v)
	}
	return _c
}

// SetLookupKey sets the "lookup_key" field.
func (_c *FeatureCreate) SetLookupKey(v string) *FeatureCreate {
	_c.mutation.SetLookupKey(v)
	return _c
}

// SetName sets the "name" field.
func (_c *FeatureCreate) SetName(v string) *FeatureCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *FeatureCreate) SetDescription(v string) *FeatureCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *FeatureCreate) SetNillableDescription(v *string) *FeatureCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *FeatureCreate) SetType(v string) *FeatureCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetMeterID sets the "meter_id" field.
func (_c *FeatureCreate) SetMeterID(v string) *FeatureCreate {
	_c.mutation.SetMeterID(v)
	return _c
}

// SetNillableMeterID sets the "meter_id" field if the given value is not nil.
func (_c *FeatureCreate) SetNillableMeterID(v *string) *FeatureCreate {
	if v != nil {
		_c.SetMeterID(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *FeatureCreate) SetMetadata(v map[string]string) *FeatureCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetUnitSingular sets the "unit_singular" field.
func (_c *FeatureCreate) SetUnitSingular(v string) *FeatureCreate {
	_c.mutation.SetUnitSingular(v)
	return _c
}

// SetNillableUnitSingular sets the "unit_singular" field if the given value is not nil.
func (_c *FeatureCreate) SetNillableUnitSingular(v *string) *FeatureCreate {
	if v != nil {
		_c.SetUnitSingular(*v)
	}
	return _c
}

// SetUnitPlural sets the "unit_plural" field.
func (_c *FeatureCreate) SetUnitPlural(v string) *FeatureCreate {
	_c.mutation.SetUnitPlural(v)
	return _c
}

// SetNillableUnitPlural sets the "unit_plural" field if the given value is not nil.
func (_c *FeatureCreate) SetNillableUnitPlural(v *string) *FeatureCreate {
	if v != nil {
		_c.SetUnitPlural(*v)
	}
	return _c
}

// SetReportingUnitSingular sets the "reporting_unit_singular" field.
func (_c *FeatureCreate) SetReportingUnitSingular(v string) *FeatureCreate {
	_c.mutation.SetReportingUnitSingular(v)
	return _c
}

// SetNillableReportingUnitSingular sets the "reporting_unit_singular" field if the given value is not nil.
func (_c *FeatureCreate) SetNillableReportingUnitSingular(v *string) *FeatureCreate {
	if v != nil {
		_c.SetReportingUnitSingular(*v)
	}
	return _c
}

// SetReportingUnitPlural sets the "reporting_unit_plural" field.
func (_c *FeatureCreate) SetReportingUnitPlural(v string) *FeatureCreate {
	_c.mutation.SetReportingUnitPlural(v)
	return _c
}

// SetNillableReportingUnitPlural sets the "reporting_unit_plural" field if the given value is not nil.
func (_c *FeatureCreate) SetNillableReportingUnitPlural(v *string) *FeatureCreate {
	if v != nil {
		_c.SetReportingUnitPlural(*v)
	}
	return _c
}

// SetReportingUnitConversionRate sets the "reporting_unit_conversion_rate" field.
func (_c *FeatureCreate) SetReportingUnitConversionRate(v decimal.Decimal) *FeatureCreate {
	_c.mutation.SetReportingUnitConversionRate(v)
	return _c
}

// SetNillableReportingUnitConversionRate sets the "reporting_unit_conversion_rate" field if the given value is not nil.
func (_c *FeatureCreate) SetNillableReportingUnitConversionRate(v *decimal.Decimal) *FeatureCreate {
	if v != nil {
		_c.SetReportingUnitConversionRate(*v)
	}
	return _c
}

// SetAlertSettings sets the "alert_settings" field.
func (_c *FeatureCreate) SetAlertSettings(v types.AlertSettings) *FeatureCreate {
	_c.mutation.SetAlertSettings(v)
	return _c
}

// SetNillableAlertSettings sets the "alert_settings" field if the given value is not nil.
func (_c *FeatureCreate) SetNillableAlertSettings(v *types.AlertSettings) *FeatureCreate {
	if v != nil {
		_c.SetAlertSettings(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *FeatureCreate) SetGroupID(v string) *FeatureCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_c *FeatureCreate) SetNillableGroupID(v *string) *FeatureCreate {
	if v != nil {
		_c.SetGroupID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *FeatureCreate) SetID(v string) *FeatureCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the FeatureMutation object of the builder.
func (_c *FeatureCreate) Mutation() *FeatureMutation {
	return _c.mutation
}

// Save creates the Feature in the database.
func (_c *FeatureCreate) Save(ctx context.Context) (*Feature, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FeatureCreate) SaveX(ctx context.Context) *Feature {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FeatureCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FeatureCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FeatureCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := feature.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := feature.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := feature.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.EnvironmentID(); !ok {
		v := feature.DefaultEnvironmentID
		_c.mutation.SetEnvironmentID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FeatureCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Feature.tenant_id"`)}
	}
	if v, ok := _c.mutation.TenantID(); ok {
		if err := feature.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "Feature.tenant_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Feature.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Feature.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Feature.updated_at"`)}
	}
	if _, ok := _c.mutation.LookupKey(); !ok {
		return &ValidationError{Name: "lookup_key", err: errors.New(`ent: missing required field "Feature.lookup_key"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Feature.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := feature.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Feature.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Feature.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := feature.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Feature.type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.AlertSettings(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "alert_settings", err: fmt.Errorf(`ent: validator failed for field "Feature.alert_settings": %w`, err)}
		}
	}
	return nil
}

func (_c *FeatureCreate) sqlSave(ctx context.Context) (*Feature, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Feature.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FeatureCreate) createSpec() (*Feature, *sqlgraph.CreateSpec) {
	var (
		_node = &Feature{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(feature.Table, sqlgraph.NewFieldSpec(feature.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(feature.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(feature.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(feature.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(feature.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(feature.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(feature.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	if value, ok := _c.mutation.EnvironmentID(); ok {
		_spec.SetField(feature.FieldEnvironmentID, field.TypeString, value)
		_node.EnvironmentID = value
	}
	if value, ok := _c.mutation.LookupKey(); ok {
		_spec.SetField(feature.FieldLookupKey, field.TypeString, value)
		_node.LookupKey = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(feature.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(feature.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(feature.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.MeterID(); ok {
		_spec.SetField(feature.FieldMeterID, field.TypeString, value)
		_node.MeterID = &value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(feature.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.UnitSingular(); ok {
		_spec.SetField(feature.FieldUnitSingular, field.TypeString, value)
		_node.UnitSingular = &value
	}
	if value, ok := _c.mutation.UnitPlural(); ok {
		_spec.SetField(feature.FieldUnitPlural, field.TypeString, value)
		_node.UnitPlural = &value
	}
	if value, ok := _c.mutation.ReportingUnitSingular(); ok {
		_spec.SetField(feature.FieldReportingUnitSingular, field.TypeString, value)
		_node.ReportingUnitSingular = &value
	}
	if value, ok := _c.mutation.ReportingUnitPlural(); ok {
		_spec.SetField(feature.FieldReportingUnitPlural, field.TypeString, value)
		_node.ReportingUnitPlural = &value
	}
	if value, ok := _c.mutation.ReportingUnitConversionRate(); ok {
		_spec.SetField(feature.FieldReportingUnitConversionRate, field.TypeOther, value)
		_node.ReportingUnitConversionRate = &value
	}
	if value, ok := _c.mutation.AlertSettings(); ok {
		_spec.SetField(feature.FieldAlertSettings, field.TypeJSON, value)
		_node.AlertSettings = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(feature.FieldGroupID, field.TypeString, value)
		_node.GroupID = &value
	}
	return _node, _spec
}

// FeatureCreateBulk is the builder for creating many Feature entities in bulk.
type FeatureCreateBulk struct {
	config
	err      error
	builders []*FeatureCreate
}

// Save creates the Feature entities in the database.
func (_c *FeatureCreateBulk) Save(ctx context.Context) ([]*Feature, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Feature, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FeatureMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FeatureCreateBulk) SaveX(ctx context.Context) []*Feature {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FeatureCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FeatureCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
