// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/payment"
	"github.com/flexprice/flexprice/ent/paymentattempt"
	"github.com/flexprice/flexprice/ent/predicate"
)

// PaymentAttemptQuery is the builder for querying PaymentAttempt entities.
type PaymentAttemptQuery struct {
	config
	ctx         *QueryContext
	order       []paymentattempt.OrderOption
	inters      []Interceptor
	predicates  []predicate.PaymentAttempt
	withPayment *PaymentQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PaymentAttemptQuery builder.
func (_q *PaymentAttemptQuery) Where(ps ...predicate.PaymentAttempt) *PaymentAttemptQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *PaymentAttemptQuery) Limit(limit int) *PaymentAttemptQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *PaymentAttemptQuery) Offset(offset int) *PaymentAttemptQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *PaymentAttemptQuery) Unique(unique bool) *PaymentAttemptQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *PaymentAttemptQuery) Order(o ...paymentattempt.OrderOption) *PaymentAttemptQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryPayment chains the current query on the "payment" edge.
func (_q *PaymentAttemptQuery) QueryPayment() *PaymentQuery {
	query := (&PaymentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(paymentattempt.Table, paymentattempt.FieldID, selector),
			sqlgraph.To(payment.Table, payment.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, paymentattempt.PaymentTable, paymentattempt.PaymentColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PaymentAttempt entity from the query.
// Returns a *NotFoundError when no PaymentAttempt was found.
func (_q *PaymentAttemptQuery) First(ctx context.Context) (*PaymentAttempt, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{paymentattempt.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *PaymentAttemptQuery) FirstX(ctx context.Context) *PaymentAttempt {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PaymentAttempt ID from the query.
// Returns a *NotFoundError when no PaymentAttempt ID was found.
func (_q *PaymentAttemptQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{paymentattempt.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *PaymentAttemptQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PaymentAttempt entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PaymentAttempt entity is found.
// Returns a *NotFoundError when no PaymentAttempt entities are found.
func (_q *PaymentAttemptQuery) Only(ctx context.Context) (*PaymentAttempt, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{paymentattempt.Label}
	default:
		return nil, &NotSingularError{paymentattempt.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *PaymentAttemptQuery) OnlyX(ctx context.Context) *PaymentAttempt {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PaymentAttempt ID in the query.
// Returns a *NotSingularError when more than one PaymentAttempt ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *PaymentAttemptQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{paymentattempt.Label}
	default:
		err = &NotSingularError{paymentattempt.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *PaymentAttemptQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PaymentAttempts.
func (_q *PaymentAttemptQuery) All(ctx context.Context) ([]*PaymentAttempt, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PaymentAttempt, *PaymentAttemptQuery]()
	return withInterceptors[[]*PaymentAttempt](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *PaymentAttemptQuery) AllX(ctx context.Context) []*PaymentAttempt {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PaymentAttempt IDs.
func (_q *PaymentAttemptQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(paymentattempt.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *PaymentAttemptQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *PaymentAttemptQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*PaymentAttemptQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *PaymentAttemptQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *PaymentAttemptQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *PaymentAttemptQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PaymentAttemptQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *PaymentAttemptQuery) Clone() *PaymentAttemptQuery {
	if _q == nil {
		return nil
	}
	return &PaymentAttemptQuery{
		config:      _q.config,
		ctx:         _q.ctx.Clone(),
		order:       append([]paymentattempt.OrderOption{}, _q.order...),
		inters:      append([]Interceptor{}, _q.inters...),
		predicates:  append([]predicate.PaymentAttempt{}, _q.predicates...),
		withPayment: _q.withPayment.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithPayment tells the query-builder to eager-load the nodes that are connected to
// the "payment" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PaymentAttemptQuery) WithPayment(opts ...func(*PaymentQuery)) *PaymentAttemptQuery {
	query := (&PaymentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPayment = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PaymentAttempt.Query().
//		GroupBy(paymentattempt.FieldTenantID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *PaymentAttemptQuery) GroupBy(field string, fields ...string) *PaymentAttemptGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PaymentAttemptGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = paymentattempt.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//	}
//
//	client.PaymentAttempt.Query().
//		Select(paymentattempt.FieldTenantID).
//		Scan(ctx, &v)
func (_q *PaymentAttemptQuery) Select(fields ...string) *PaymentAttemptSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &PaymentAttemptSelect{PaymentAttemptQuery: _q}
	sbuild.label = paymentattempt.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PaymentAttemptSelect configured with the given aggregations.
func (_q *PaymentAttemptQuery) Aggregate(fns ...AggregateFunc) *PaymentAttemptSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *PaymentAttemptQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !paymentattempt.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *PaymentAttemptQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PaymentAttempt, error) {
	var (
		nodes       = []*PaymentAttempt{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withPayment != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PaymentAttempt).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PaymentAttempt{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withPayment; query != nil {
		if err := _q.loadPayment(ctx, query, nodes, nil,
			func(n *PaymentAttempt, e *Payment) { n.Edges.Payment = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *PaymentAttemptQuery) loadPayment(ctx context.Context, query *PaymentQuery, nodes []*PaymentAttempt, init func(*PaymentAttempt), assign func(*PaymentAttempt, *Payment)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*PaymentAttempt)
	for i := range nodes {
		fk := nodes[i].PaymentID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(payment.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "payment_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *PaymentAttemptQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *PaymentAttemptQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(paymentattempt.Table, paymentattempt.Columns, sqlgraph.NewFieldSpec(paymentattempt.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymentattempt.FieldID)
		for i := range fields {
			if fields[i] != paymentattempt.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withPayment != nil {
			_spec.Node.AddColumnOnce(paymentattempt.FieldPaymentID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *PaymentAttemptQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(paymentattempt.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = paymentattempt.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PaymentAttemptGroupBy is the group-by builder for PaymentAttempt entities.
type PaymentAttemptGroupBy struct {
	selector
	build *PaymentAttemptQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *PaymentAttemptGroupBy) Aggregate(fns ...AggregateFunc) *PaymentAttemptGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *PaymentAttemptGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PaymentAttemptQuery, *PaymentAttemptGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *PaymentAttemptGroupBy) sqlScan(ctx context.Context, root *PaymentAttemptQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PaymentAttemptSelect is the builder for selecting fields of PaymentAttempt entities.
type PaymentAttemptSelect struct {
	*PaymentAttemptQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *PaymentAttemptSelect) Aggregate(fns ...AggregateFunc) *PaymentAttemptSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *PaymentAttemptSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PaymentAttemptQuery, *PaymentAttemptSelect](ctx, _s.PaymentAttemptQuery, _s, _s.inters, v)
}

func (_s *PaymentAttemptSelect) sqlScan(ctx context.Context, root *PaymentAttemptQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
