// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/flexprice/flexprice/ent/refund"
	"github.com/shopspring/decimal"
)

// Refund is the model entity for the Refund schema.
type Refund struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID string `json:"tenant_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy string `json:"created_by,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy string `json:"updated_by,omitempty"`
	// EnvironmentID holds the value of the "environment_id" field.
	EnvironmentID string `json:"environment_id,omitempty"`
	// PaymentID holds the value of the "payment_id" field.
	PaymentID *string `json:"payment_id,omitempty"`
	// InvoiceID holds the value of the "invoice_id" field.
	InvoiceID string `json:"invoice_id,omitempty"`
	// CreditNoteID holds the value of the "credit_note_id" field.
	CreditNoteID *string `json:"credit_note_id,omitempty"`
	// PaymentGateway holds the value of the "payment_gateway" field.
	PaymentGateway *string `json:"payment_gateway,omitempty"`
	// GatewayRefundID holds the value of the "gateway_refund_id" field.
	GatewayRefundID *string `json:"gateway_refund_id,omitempty"`
	// GatewayTrackingID holds the value of the "gateway_tracking_id" field.
	GatewayTrackingID *string `json:"gateway_tracking_id,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount decimal.Decimal `json:"amount,omitempty"`
	// SettledAmount holds the value of the "settled_amount" field.
	SettledAmount decimal.Decimal `json:"settled_amount,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// RefundStatus holds the value of the "refund_status" field.
	RefundStatus string `json:"refund_status,omitempty"`
	// RefundReason holds the value of the "refund_reason" field.
	RefundReason string `json:"refund_reason,omitempty"`
	// RefundDestination holds the value of the "refund_destination" field.
	RefundDestination string `json:"refund_destination,omitempty"`
	// RefundDestinationID holds the value of the "refund_destination_id" field.
	RefundDestinationID *string `json:"refund_destination_id,omitempty"`
	// Attempt holds the value of the "attempt" field.
	Attempt int `json:"attempt,omitempty"`
	// IdempotencyKey holds the value of the "idempotency_key" field.
	IdempotencyKey string `json:"idempotency_key,omitempty"`
	// GatewayIdempotencyToken holds the value of the "gateway_idempotency_token" field.
	GatewayIdempotencyToken *string `json:"gateway_idempotency_token,omitempty"`
	// FailureReason holds the value of the "failure_reason" field.
	FailureReason *string `json:"failure_reason,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]string `json:"metadata,omitempty"`
	// GatewayMetadata holds the value of the "gateway_metadata" field.
	GatewayMetadata map[string]interface{} `json:"gateway_metadata,omitempty"`
	// InitiatedAt holds the value of the "initiated_at" field.
	InitiatedAt *time.Time `json:"initiated_at,omitempty"`
	// SucceededAt holds the value of the "succeeded_at" field.
	SucceededAt *time.Time `json:"succeeded_at,omitempty"`
	// FailedAt holds the value of the "failed_at" field.
	FailedAt *time.Time `json:"failed_at,omitempty"`
	// CancelledAt holds the value of the "cancelled_at" field.
	CancelledAt  *time.Time `json:"cancelled_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Refund) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case refund.FieldMetadata, refund.FieldGatewayMetadata:
			values[i] = new([]byte)
		case refund.FieldAmount, refund.FieldSettledAmount:
			values[i] = new(decimal.Decimal)
		case refund.FieldAttempt:
			values[i] = new(sql.NullInt64)
		case refund.FieldID, refund.FieldTenantID, refund.FieldStatus, refund.FieldCreatedBy, refund.FieldUpdatedBy, refund.FieldEnvironmentID, refund.FieldPaymentID, refund.FieldInvoiceID, refund.FieldCreditNoteID, refund.FieldPaymentGateway, refund.FieldGatewayRefundID, refund.FieldGatewayTrackingID, refund.FieldCurrency, refund.FieldRefundStatus, refund.FieldRefundReason, refund.FieldRefundDestination, refund.FieldRefundDestinationID, refund.FieldIdempotencyKey, refund.FieldGatewayIdempotencyToken, refund.FieldFailureReason:
			values[i] = new(sql.NullString)
		case refund.FieldCreatedAt, refund.FieldUpdatedAt, refund.FieldInitiatedAt, refund.FieldSucceededAt, refund.FieldFailedAt, refund.FieldCancelledAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Refund fields.
func (r *Refund) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case refund.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				r.ID = value.String
			}
		case refund.FieldTenantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				r.TenantID = value.String
			}
		case refund.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				r.Status = value.String
			}
		case refund.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				r.CreatedAt = value.Time
			}
		case refund.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				r.UpdatedAt = value.Time
			}
		case refund.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				r.CreatedBy = value.String
			}
		case refund.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				r.UpdatedBy = value.String
			}
		case refund.FieldEnvironmentID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field environment_id", values[i])
			} else if value.Valid {
				r.EnvironmentID = value.String
			}
		case refund.FieldPaymentID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payment_id", values[i])
			} else if value.Valid {
				r.PaymentID = new(string)
				*r.PaymentID = value.String
			}
		case refund.FieldInvoiceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field invoice_id", values[i])
			} else if value.Valid {
				r.InvoiceID = value.String
			}
		case refund.FieldCreditNoteID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field credit_note_id", values[i])
			} else if value.Valid {
				r.CreditNoteID = new(string)
				*r.CreditNoteID = value.String
			}
		case refund.FieldPaymentGateway:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payment_gateway", values[i])
			} else if value.Valid {
				r.PaymentGateway = new(string)
				*r.PaymentGateway = value.String
			}
		case refund.FieldGatewayRefundID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field gateway_refund_id", values[i])
			} else if value.Valid {
				r.GatewayRefundID = new(string)
				*r.GatewayRefundID = value.String
			}
		case refund.FieldGatewayTrackingID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field gateway_tracking_id", values[i])
			} else if value.Valid {
				r.GatewayTrackingID = new(string)
				*r.GatewayTrackingID = value.String
			}
		case refund.FieldAmount:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value != nil {
				r.Amount = *value
			}
		case refund.FieldSettledAmount:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field settled_amount", values[i])
			} else if value != nil {
				r.SettledAmount = *value
			}
		case refund.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				r.Currency = value.String
			}
		case refund.FieldRefundStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refund_status", values[i])
			} else if value.Valid {
				r.RefundStatus = value.String
			}
		case refund.FieldRefundReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refund_reason", values[i])
			} else if value.Valid {
				r.RefundReason = value.String
			}
		case refund.FieldRefundDestination:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refund_destination", values[i])
			} else if value.Valid {
				r.RefundDestination = value.String
			}
		case refund.FieldRefundDestinationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refund_destination_id", values[i])
			} else if value.Valid {
				r.RefundDestinationID = new(string)
				*r.RefundDestinationID = value.String
			}
		case refund.FieldAttempt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempt", values[i])
			} else if value.Valid {
				r.Attempt = int(value.Int64)
			}
		case refund.FieldIdempotencyKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key", values[i])
			} else if value.Valid {
				r.IdempotencyKey = value.String
			}
		case refund.FieldGatewayIdempotencyToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field gateway_idempotency_token", values[i])
			} else if value.Valid {
				r.GatewayIdempotencyToken = new(string)
				*r.GatewayIdempotencyToken = value.String
			}
		case refund.FieldFailureReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field failure_reason", values[i])
			} else if value.Valid {
				r.FailureReason = new(string)
				*r.FailureReason = value.String
			}
		case refund.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &r.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case refund.FieldGatewayMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field gateway_metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &r.GatewayMetadata); err != nil {
					return fmt.Errorf("unmarshal field gateway_metadata: %w", err)
				}
			}
		case refund.FieldInitiatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field initiated_at", values[i])
			} else if value.Valid {
				r.InitiatedAt = new(time.Time)
				*r.InitiatedAt = value.Time
			}
		case refund.FieldSucceededAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field succeeded_at", values[i])
			} else if value.Valid {
				r.SucceededAt = new(time.Time)
				*r.SucceededAt = value.Time
			}
		case refund.FieldFailedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field failed_at", values[i])
			} else if value.Valid {
				r.FailedAt = new(time.Time)
				*r.FailedAt = value.Time
			}
		case refund.FieldCancelledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field cancelled_at", values[i])
			} else if value.Valid {
				r.CancelledAt = new(time.Time)
				*r.CancelledAt = value.Time
			}
		default:
			r.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Refund.
// This includes values selected through modifiers, order, etc.
func (r *Refund) Value(name string) (ent.Value, error) {
	return r.selectValues.Get(name)
}

// Update returns a builder for updating this Refund.
// Note that you need to call Refund.Unwrap() before calling this method if this Refund
// was returned from a transaction, and the transaction was committed or rolled back.
func (r *Refund) Update() *RefundUpdateOne {
	return NewRefundClient(r.config).UpdateOne(r)
}

// Unwrap unwraps the Refund entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (r *Refund) Unwrap() *Refund {
	_tx, ok := r.config.driver.(*txDriver)
	if !ok {
		panic("ent: Refund is not a transactional entity")
	}
	r.config.driver = _tx.drv
	return r
}

// String implements the fmt.Stringer.
func (r *Refund) String() string {
	var builder strings.Builder
	builder.WriteString("Refund(")
	builder.WriteString(fmt.Sprintf("id=%v, ", r.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(r.TenantID)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(r.Status)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(r.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(r.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(r.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(r.UpdatedBy)
	builder.WriteString(", ")
	builder.WriteString("environment_id=")
	builder.WriteString(r.EnvironmentID)
	builder.WriteString(", ")
	if v := r.PaymentID; v != nil {
		builder.WriteString("payment_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("invoice_id=")
	builder.WriteString(r.InvoiceID)
	builder.WriteString(", ")
	if v := r.CreditNoteID; v != nil {
		builder.WriteString("credit_note_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := r.PaymentGateway; v != nil {
		builder.WriteString("payment_gateway=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := r.GatewayRefundID; v != nil {
		builder.WriteString("gateway_refund_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := r.GatewayTrackingID; v != nil {
		builder.WriteString("gateway_tracking_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", r.Amount))
	builder.WriteString(", ")
	builder.WriteString("settled_amount=")
	builder.WriteString(fmt.Sprintf("%v", r.SettledAmount))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(r.Currency)
	builder.WriteString(", ")
	builder.WriteString("refund_status=")
	builder.WriteString(r.RefundStatus)
	builder.WriteString(", ")
	builder.WriteString("refund_reason=")
	builder.WriteString(r.RefundReason)
	builder.WriteString(", ")
	builder.WriteString("refund_destination=")
	builder.WriteString(r.RefundDestination)
	builder.WriteString(", ")
	if v := r.RefundDestinationID; v != nil {
		builder.WriteString("refund_destination_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("attempt=")
	builder.WriteString(fmt.Sprintf("%v", r.Attempt))
	builder.WriteString(", ")
	builder.WriteString("idempotency_key=")
	builder.WriteString(r.IdempotencyKey)
	builder.WriteString(", ")
	if v := r.GatewayIdempotencyToken; v != nil {
		builder.WriteString("gateway_idempotency_token=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := r.FailureReason; v != nil {
		builder.WriteString("failure_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", r.Metadata))
	builder.WriteString(", ")
	builder.WriteString("gateway_metadata=")
	builder.WriteString(fmt.Sprintf("%v", r.GatewayMetadata))
	builder.WriteString(", ")
	if v := r.InitiatedAt; v != nil {
		builder.WriteString("initiated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := r.SucceededAt; v != nil {
		builder.WriteString("succeeded_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := r.FailedAt; v != nil {
		builder.WriteString("failed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := r.CancelledAt; v != nil {
		builder.WriteString("cancelled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Refunds is a parsable slice of Refund.
type Refunds []*Refund
