// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/predicate"
	"github.com/flexprice/flexprice/ent/refund"
	"github.com/shopspring/decimal"
)

// RefundUpdate is the builder for updating Refund entities.
type RefundUpdate struct {
	config
	hooks    []Hook
	mutation *RefundMutation
}

// Where appends a list predicates to the RefundUpdate builder.
func (_u *RefundUpdate) Where(ps ...predicate.Refund) *RefundUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *RefundUpdate) SetStatus(v string) *RefundUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RefundUpdate) SetNillableStatus(v *string) *RefundUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RefundUpdate) SetUpdatedAt(v time.Time) *RefundUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *RefundUpdate) SetUpdatedBy(v string) *RefundUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *RefundUpdate) SetNillableUpdatedBy(v *string) *RefundUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *RefundUpdate) ClearUpdatedBy() *RefundUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetGatewayRefundID sets the "gateway_refund_id" field.
func (_u *RefundUpdate) SetGatewayRefundID(v string) *RefundUpdate {
	_u.mutation.SetGatewayRefundID(v)
	return _u
}

// SetNillableGatewayRefundID sets the "gateway_refund_id" field if the given value is not nil.
func (_u *RefundUpdate) SetNillableGatewayRefundID(v *string) *RefundUpdate {
	if v != nil {
		_u.SetGatewayRefundID(*v)
	}
	return _u
}

// ClearGatewayRefundID clears the value of the "gateway_refund_id" field.
func (_u *RefundUpdate) ClearGatewayRefundID() *RefundUpdate {
	_u.mutation.ClearGatewayRefundID()
	return _u
}

// SetGatewayTrackingID sets the "gateway_tracking_id" field.
func (_u *RefundUpdate) SetGatewayTrackingID(v string) *RefundUpdate {
	_u.mutation.SetGatewayTrackingID(v)
	return _u
}

// SetNillableGatewayTrackingID sets the "gateway_tracking_id" field if the given value is not nil.
func (_u *RefundUpdate) SetNillableGatewayTrackingID(v *string) *RefundUpdate {
	if v != nil {
		_u.SetGatewayTrackingID(*v)
	}
	return _u
}

// ClearGatewayTrackingID clears the value of the "gateway_tracking_id" field.
func (_u *RefundUpdate) ClearGatewayTrackingID() *RefundUpdate {
	_u.mutation.ClearGatewayTrackingID()
	return _u
}

// SetAmount sets the "amount" field.
func (_u *RefundUpdate) SetAmount(v decimal.Decimal) *RefundUpdate {
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *RefundUpdate) SetNillableAmount(v *decimal.Decimal) *RefundUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// SetSettledAmount sets the "settled_amount" field.
func (_u *RefundUpdate) SetSettledAmount(v decimal.Decimal) *RefundUpdate {
	_u.mutation.SetSettledAmount(v)
	return _u
}

// SetNillableSettledAmount sets the "settled_amount" field if the given value is not nil.
func (_u *RefundUpdate) SetNillableSettledAmount(v *decimal.Decimal) *RefundUpdate {
	if v != nil {
		_u.SetSettledAmount(*v)
	}
	return _u
}

// SetRefundStatus sets the "refund_status" field.
func (_u *RefundUpdate) SetRefundStatus(v string) *RefundUpdate {
	_u.mutation.SetRefundStatus(v)
	return _u
}

// SetNillableRefundStatus sets the "refund_status" field if the given value is not nil.
func (_u *RefundUpdate) SetNillableRefundStatus(v *string) *RefundUpdate {
	if v != nil {
		_u.SetRefundStatus(*v)
	}
	return _u
}

// SetRefundReason sets the "refund_reason" field.
func (_u *RefundUpdate) SetRefundReason(v string) *RefundUpdate {
	_u.mutation.SetRefundReason(v)
	return _u
}

// SetNillableRefundReason sets the "refund_reason" field if the given value is not nil.
func (_u *RefundUpdate) SetNillableRefundReason(v *string) *RefundUpdate {
	if v != nil {
		_u.SetRefundReason(*v)
	}
	return _u
}

// SetRefundDestination sets the "refund_destination" field.
func (_u *RefundUpdate) SetRefundDestination(v string) *RefundUpdate {
	_u.mutation.SetRefundDestination(v)
	return _u
}

// SetNillableRefundDestination sets the "refund_destination" field if the given value is not nil.
func (_u *RefundUpdate) SetNillableRefundDestination(v *string) *RefundUpdate {
	if v != nil {
		_u.SetRefundDestination(*v)
	}
	return _u
}

// SetRefundDestinationID sets the "refund_destination_id" field.
func (_u *RefundUpdate) SetRefundDestinationID(v string) *RefundUpdate {
	_u.mutation.SetRefundDestinationID(v)
	return _u
}

// SetNillableRefundDestinationID sets the "refund_destination_id" field if the given value is not nil.
func (_u *RefundUpdate) SetNillableRefundDestinationID(v *string) *RefundUpdate {
	if v != nil {
		_u.SetRefundDestinationID(*v)
	}
	return _u
}

// ClearRefundDestinationID clears the value of the "refund_destination_id" field.
func (_u *RefundUpdate) ClearRefundDestinationID() *RefundUpdate {
	_u.mutation.ClearRefundDestinationID()
	return _u
}

// SetAttempt sets the "attempt" field.
func (_u *RefundUpdate) SetAttempt(v int) *RefundUpdate {
	_u.mutation.ResetAttempt()
	_u.mutation.SetAttempt(v)
	return _u
}

// SetNillableAttempt sets the "attempt" field if the given value is not nil.
func (_u *RefundUpdate) SetNillableAttempt(v *int) *RefundUpdate {
	if v != nil {
		_u.SetAttempt(*v)
	}
	return _u
}

// AddAttempt adds value to the "attempt" field.
func (_u *RefundUpdate) AddAttempt(v int) *RefundUpdate {
	_u.mutation.AddAttempt(v)
	return _u
}

// SetFailureReason sets the "failure_reason" field.
func (_u *RefundUpdate) SetFailureReason(v string) *RefundUpdate {
	_u.mutation.SetFailureReason(v)
	return _u
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (_u *RefundUpdate) SetNillableFailureReason(v *string) *RefundUpdate {
	if v != nil {
		_u.SetFailureReason(*v)
	}
	return _u
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (_u *RefundUpdate) ClearFailureReason() *RefundUpdate {
	_u.mutation.ClearFailureReason()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *RefundUpdate) SetMetadata(v map[string]string) *RefundUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *RefundUpdate) ClearMetadata() *RefundUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetGatewayMetadata sets the "gateway_metadata" field.
func (_u *RefundUpdate) SetGatewayMetadata(v map[string]interface{}) *RefundUpdate {
	_u.mutation.SetGatewayMetadata(v)
	return _u
}

// ClearGatewayMetadata clears the value of the "gateway_metadata" field.
func (_u *RefundUpdate) ClearGatewayMetadata() *RefundUpdate {
	_u.mutation.ClearGatewayMetadata()
	return _u
}

// SetInitiatedAt sets the "initiated_at" field.
func (_u *RefundUpdate) SetInitiatedAt(v time.Time) *RefundUpdate {
	_u.mutation.SetInitiatedAt(v)
	return _u
}

// SetNillableInitiatedAt sets the "initiated_at" field if the given value is not nil.
func (_u *RefundUpdate) SetNillableInitiatedAt(v *time.Time) *RefundUpdate {
	if v != nil {
		_u.SetInitiatedAt(*v)
	}
	return _u
}

// ClearInitiatedAt clears the value of the "initiated_at" field.
func (_u *RefundUpdate) ClearInitiatedAt() *RefundUpdate {
	_u.mutation.ClearInitiatedAt()
	return _u
}

// SetSucceededAt sets the "succeeded_at" field.
func (_u *RefundUpdate) SetSucceededAt(v time.Time) *RefundUpdate {
	_u.mutation.SetSucceededAt(v)
	return _u
}

// SetNillableSucceededAt sets the "succeeded_at" field if the given value is not nil.
func (_u *RefundUpdate) SetNillableSucceededAt(v *time.Time) *RefundUpdate {
	if v != nil {
		_u.SetSucceededAt(*v)
	}
	return _u
}

// ClearSucceededAt clears the value of the "succeeded_at" field.
func (_u *RefundUpdate) ClearSucceededAt() *RefundUpdate {
	_u.mutation.ClearSucceededAt()
	return _u
}

// SetFailedAt sets the "failed_at" field.
func (_u *RefundUpdate) SetFailedAt(v time.Time) *RefundUpdate {
	_u.mutation.SetFailedAt(v)
	return _u
}

// SetNillableFailedAt sets the "failed_at" field if the given value is not nil.
func (_u *RefundUpdate) SetNillableFailedAt(v *time.Time) *RefundUpdate {
	if v != nil {
		_u.SetFailedAt(*v)
	}
	return _u
}

// ClearFailedAt clears the value of the "failed_at" field.
func (_u *RefundUpdate) ClearFailedAt() *RefundUpdate {
	_u.mutation.ClearFailedAt()
	return _u
}

// SetCancelledAt sets the "cancelled_at" field.
func (_u *RefundUpdate) SetCancelledAt(v time.Time) *RefundUpdate {
	_u.mutation.SetCancelledAt(v)
	return _u
}

// SetNillableCancelledAt sets the "cancelled_at" field if the given value is not nil.
func (_u *RefundUpdate) SetNillableCancelledAt(v *time.Time) *RefundUpdate {
	if v != nil {
		_u.SetCancelledAt(*v)
	}
	return _u
}

// ClearCancelledAt clears the value of the "cancelled_at" field.
func (_u *RefundUpdate) ClearCancelledAt() *RefundUpdate {
	_u.mutation.ClearCancelledAt()
	return _u
}

// Mutation returns the RefundMutation object of the builder.
func (_u *RefundUpdate) Mutation() *RefundMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RefundUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RefundUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RefundUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RefundUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RefundUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := refund.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RefundUpdate) check() error {
	if v, ok := _u.mutation.RefundStatus(); ok {
		if err := refund.RefundStatusValidator(v); err != nil {
			return &ValidationError{Name: "refund_status", err: fmt.Errorf(`ent: validator failed for field "Refund.refund_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RefundReason(); ok {
		if err := refund.RefundReasonValidator(v); err != nil {
			return &ValidationError{Name: "refund_reason", err: fmt.Errorf(`ent: validator failed for field "Refund.refund_reason": %w`, err)}
		}
	}
	return nil
}

func (_u *RefundUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(refund.Table, refund.Columns, sqlgraph.NewFieldSpec(refund.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(refund.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(refund.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(refund.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(refund.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(refund.FieldUpdatedBy, field.TypeString)
	}
	if _u.mutation.EnvironmentIDCleared() {
		_spec.ClearField(refund.FieldEnvironmentID, field.TypeString)
	}
	if _u.mutation.PaymentIDCleared() {
		_spec.ClearField(refund.FieldPaymentID, field.TypeString)
	}
	if _u.mutation.CreditNoteIDCleared() {
		_spec.ClearField(refund.FieldCreditNoteID, field.TypeString)
	}
	if _u.mutation.PaymentGatewayCleared() {
		_spec.ClearField(refund.FieldPaymentGateway, field.TypeString)
	}
	if value, ok := _u.mutation.GatewayRefundID(); ok {
		_spec.SetField(refund.FieldGatewayRefundID, field.TypeString, value)
	}
	if _u.mutation.GatewayRefundIDCleared() {
		_spec.ClearField(refund.FieldGatewayRefundID, field.TypeString)
	}
	if value, ok := _u.mutation.GatewayTrackingID(); ok {
		_spec.SetField(refund.FieldGatewayTrackingID, field.TypeString, value)
	}
	if _u.mutation.GatewayTrackingIDCleared() {
		_spec.ClearField(refund.FieldGatewayTrackingID, field.TypeString)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(refund.FieldAmount, field.TypeOther, value)
	}
	if value, ok := _u.mutation.SettledAmount(); ok {
		_spec.SetField(refund.FieldSettledAmount, field.TypeOther, value)
	}
	if value, ok := _u.mutation.RefundStatus(); ok {
		_spec.SetField(refund.FieldRefundStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefundReason(); ok {
		_spec.SetField(refund.FieldRefundReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefundDestination(); ok {
		_spec.SetField(refund.FieldRefundDestination, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefundDestinationID(); ok {
		_spec.SetField(refund.FieldRefundDestinationID, field.TypeString, value)
	}
	if _u.mutation.RefundDestinationIDCleared() {
		_spec.ClearField(refund.FieldRefundDestinationID, field.TypeString)
	}
	if value, ok := _u.mutation.Attempt(); ok {
		_spec.SetField(refund.FieldAttempt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempt(); ok {
		_spec.AddField(refund.FieldAttempt, field.TypeInt, value)
	}
	if _u.mutation.GatewayIdempotencyTokenCleared() {
		_spec.ClearField(refund.FieldGatewayIdempotencyToken, field.TypeString)
	}
	if value, ok := _u.mutation.FailureReason(); ok {
		_spec.SetField(refund.FieldFailureReason, field.TypeString, value)
	}
	if _u.mutation.FailureReasonCleared() {
		_spec.ClearField(refund.FieldFailureReason, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(refund.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(refund.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.GatewayMetadata(); ok {
		_spec.SetField(refund.FieldGatewayMetadata, field.TypeJSON, value)
	}
	if _u.mutation.GatewayMetadataCleared() {
		_spec.ClearField(refund.FieldGatewayMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.InitiatedAt(); ok {
		_spec.SetField(refund.FieldInitiatedAt, field.TypeTime, value)
	}
	if _u.mutation.InitiatedAtCleared() {
		_spec.ClearField(refund.FieldInitiatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SucceededAt(); ok {
		_spec.SetField(refund.FieldSucceededAt, field.TypeTime, value)
	}
	if _u.mutation.SucceededAtCleared() {
		_spec.ClearField(refund.FieldSucceededAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FailedAt(); ok {
		_spec.SetField(refund.FieldFailedAt, field.TypeTime, value)
	}
	if _u.mutation.FailedAtCleared() {
		_spec.ClearField(refund.FieldFailedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CancelledAt(); ok {
		_spec.SetField(refund.FieldCancelledAt, field.TypeTime, value)
	}
	if _u.mutation.CancelledAtCleared() {
		_spec.ClearField(refund.FieldCancelledAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{refund.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RefundUpdateOne is the builder for updating a single Refund entity.
type RefundUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RefundMutation
}

// SetStatus sets the "status" field.
func (_u *RefundUpdateOne) SetStatus(v string) *RefundUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RefundUpdateOne) SetNillableStatus(v *string) *RefundUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RefundUpdateOne) SetUpdatedAt(v time.Time) *RefundUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *RefundUpdateOne) SetUpdatedBy(v string) *RefundUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *RefundUpdateOne) SetNillableUpdatedBy(v *string) *RefundUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *RefundUpdateOne) ClearUpdatedBy() *RefundUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetGatewayRefundID sets the "gateway_refund_id" field.
func (_u *RefundUpdateOne) SetGatewayRefundID(v string) *RefundUpdateOne {
	_u.mutation.SetGatewayRefundID(v)
	return _u
}

// SetNillableGatewayRefundID sets the "gateway_refund_id" field if the given value is not nil.
func (_u *RefundUpdateOne) SetNillableGatewayRefundID(v *string) *RefundUpdateOne {
	if v != nil {
		_u.SetGatewayRefundID(*v)
	}
	return _u
}

// ClearGatewayRefundID clears the value of the "gateway_refund_id" field.
func (_u *RefundUpdateOne) ClearGatewayRefundID() *RefundUpdateOne {
	_u.mutation.ClearGatewayRefundID()
	return _u
}

// SetGatewayTrackingID sets the "gateway_tracking_id" field.
func (_u *RefundUpdateOne) SetGatewayTrackingID(v string) *RefundUpdateOne {
	_u.mutation.SetGatewayTrackingID(v)
	return _u
}

// SetNillableGatewayTrackingID sets the "gateway_tracking_id" field if the given value is not nil.
func (_u *RefundUpdateOne) SetNillableGatewayTrackingID(v *string) *RefundUpdateOne {
	if v != nil {
		_u.SetGatewayTrackingID(*v)
	}
	return _u
}

// ClearGatewayTrackingID clears the value of the "gateway_tracking_id" field.
func (_u *RefundUpdateOne) ClearGatewayTrackingID() *RefundUpdateOne {
	_u.mutation.ClearGatewayTrackingID()
	return _u
}

// SetAmount sets the "amount" field.
func (_u *RefundUpdateOne) SetAmount(v decimal.Decimal) *RefundUpdateOne {
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *RefundUpdateOne) SetNillableAmount(v *decimal.Decimal) *RefundUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// SetSettledAmount sets the "settled_amount" field.
func (_u *RefundUpdateOne) SetSettledAmount(v decimal.Decimal) *RefundUpdateOne {
	_u.mutation.SetSettledAmount(v)
	return _u
}

// SetNillableSettledAmount sets the "settled_amount" field if the given value is not nil.
func (_u *RefundUpdateOne) SetNillableSettledAmount(v *decimal.Decimal) *RefundUpdateOne {
	if v != nil {
		_u.SetSettledAmount(*v)
	}
	return _u
}

// SetRefundStatus sets the "refund_status" field.
func (_u *RefundUpdateOne) SetRefundStatus(v string) *RefundUpdateOne {
	_u.mutation.SetRefundStatus(v)
	return _u
}

// SetNillableRefundStatus sets the "refund_status" field if the given value is not nil.
func (_u *RefundUpdateOne) SetNillableRefundStatus(v *string) *RefundUpdateOne {
	if v != nil {
		_u.SetRefundStatus(*v)
	}
	return _u
}

// SetRefundReason sets the "refund_reason" field.
func (_u *RefundUpdateOne) SetRefundReason(v string) *RefundUpdateOne {
	_u.mutation.SetRefundReason(v)
	return _u
}

// SetNillableRefundReason sets the "refund_reason" field if the given value is not nil.
func (_u *RefundUpdateOne) SetNillableRefundReason(v *string) *RefundUpdateOne {
	if v != nil {
		_u.SetRefundReason(*v)
	}
	return _u
}

// SetRefundDestination sets the "refund_destination" field.
func (_u *RefundUpdateOne) SetRefundDestination(v string) *RefundUpdateOne {
	_u.mutation.SetRefundDestination(v)
	return _u
}

// SetNillableRefundDestination sets the "refund_destination" field if the given value is not nil.
func (_u *RefundUpdateOne) SetNillableRefundDestination(v *string) *RefundUpdateOne {
	if v != nil {
		_u.SetRefundDestination(*v)
	}
	return _u
}

// SetRefundDestinationID sets the "refund_destination_id" field.
func (_u *RefundUpdateOne) SetRefundDestinationID(v string) *RefundUpdateOne {
	_u.mutation.SetRefundDestinationID(v)
	return _u
}

// SetNillableRefundDestinationID sets the "refund_destination_id" field if the given value is not nil.
func (_u *RefundUpdateOne) SetNillableRefundDestinationID(v *string) *RefundUpdateOne {
	if v != nil {
		_u.SetRefundDestinationID(*v)
	}
	return _u
}

// ClearRefundDestinationID clears the value of the "refund_destination_id" field.
func (_u *RefundUpdateOne) ClearRefundDestinationID() *RefundUpdateOne {
	_u.mutation.ClearRefundDestinationID()
	return _u
}

// SetAttempt sets the "attempt" field.
func (_u *RefundUpdateOne) SetAttempt(v int) *RefundUpdateOne {
	_u.mutation.ResetAttempt()
	_u.mutation.SetAttempt(v)
	return _u
}

// SetNillableAttempt sets the "attempt" field if the given value is not nil.
func (_u *RefundUpdateOne) SetNillableAttempt(v *int) *RefundUpdateOne {
	if v != nil {
		_u.SetAttempt(*v)
	}
	return _u
}

// AddAttempt adds value to the "attempt" field.
func (_u *RefundUpdateOne) AddAttempt(v int) *RefundUpdateOne {
	_u.mutation.AddAttempt(v)
	return _u
}

// SetFailureReason sets the "failure_reason" field.
func (_u *RefundUpdateOne) SetFailureReason(v string) *RefundUpdateOne {
	_u.mutation.SetFailureReason(v)
	return _u
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (_u *RefundUpdateOne) SetNillableFailureReason(v *string) *RefundUpdateOne {
	if v != nil {
		_u.SetFailureReason(*v)
	}
	return _u
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (_u *RefundUpdateOne) ClearFailureReason() *RefundUpdateOne {
	_u.mutation.ClearFailureReason()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *RefundUpdateOne) SetMetadata(v map[string]string) *RefundUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *RefundUpdateOne) ClearMetadata() *RefundUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetGatewayMetadata sets the "gateway_metadata" field.
func (_u *RefundUpdateOne) SetGatewayMetadata(v map[string]interface{}) *RefundUpdateOne {
	_u.mutation.SetGatewayMetadata(v)
	return _u
}

// ClearGatewayMetadata clears the value of the "gateway_metadata" field.
func (_u *RefundUpdateOne) ClearGatewayMetadata() *RefundUpdateOne {
	_u.mutation.ClearGatewayMetadata()
	return _u
}

// SetInitiatedAt sets the "initiated_at" field.
func (_u *RefundUpdateOne) SetInitiatedAt(v time.Time) *RefundUpdateOne {
	_u.mutation.SetInitiatedAt(v)
	return _u
}

// SetNillableInitiatedAt sets the "initiated_at" field if the given value is not nil.
func (_u *RefundUpdateOne) SetNillableInitiatedAt(v *time.Time) *RefundUpdateOne {
	if v != nil {
		_u.SetInitiatedAt(*v)
	}
	return _u
}

// ClearInitiatedAt clears the value of the "initiated_at" field.
func (_u *RefundUpdateOne) ClearInitiatedAt() *RefundUpdateOne {
	_u.mutation.ClearInitiatedAt()
	return _u
}

// SetSucceededAt sets the "succeeded_at" field.
func (_u *RefundUpdateOne) SetSucceededAt(v time.Time) *RefundUpdateOne {
	_u.mutation.SetSucceededAt(v)
	return _u
}

// SetNillableSucceededAt sets the "succeeded_at" field if the given value is not nil.
func (_u *RefundUpdateOne) SetNillableSucceededAt(v *time.Time) *RefundUpdateOne {
	if v != nil {
		_u.SetSucceededAt(*v)
	}
	return _u
}

// ClearSucceededAt clears the value of the "succeeded_at" field.
func (_u *RefundUpdateOne) ClearSucceededAt() *RefundUpdateOne {
	_u.mutation.ClearSucceededAt()
	return _u
}

// SetFailedAt sets the "failed_at" field.
func (_u *RefundUpdateOne) SetFailedAt(v time.Time) *RefundUpdateOne {
	_u.mutation.SetFailedAt(v)
	return _u
}

// SetNillableFailedAt sets the "failed_at" field if the given value is not nil.
func (_u *RefundUpdateOne) SetNillableFailedAt(v *time.Time) *RefundUpdateOne {
	if v != nil {
		_u.SetFailedAt(*v)
	}
	return _u
}

// ClearFailedAt clears the value of the "failed_at" field.
func (_u *RefundUpdateOne) ClearFailedAt() *RefundUpdateOne {
	_u.mutation.ClearFailedAt()
	return _u
}

// SetCancelledAt sets the "cancelled_at" field.
func (_u *RefundUpdateOne) SetCancelledAt(v time.Time) *RefundUpdateOne {
	_u.mutation.SetCancelledAt(v)
	return _u
}

// SetNillableCancelledAt sets the "cancelled_at" field if the given value is not nil.
func (_u *RefundUpdateOne) SetNillableCancelledAt(v *time.Time) *RefundUpdateOne {
	if v != nil {
		_u.SetCancelledAt(*v)
	}
	return _u
}

// ClearCancelledAt clears the value of the "cancelled_at" field.
func (_u *RefundUpdateOne) ClearCancelledAt() *RefundUpdateOne {
	_u.mutation.ClearCancelledAt()
	return _u
}

// Mutation returns the RefundMutation object of the builder.
func (_u *RefundUpdateOne) Mutation() *RefundMutation {
	return _u.mutation
}

// Where appends a list predicates to the RefundUpdate builder.
func (_u *RefundUpdateOne) Where(ps ...predicate.Refund) *RefundUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RefundUpdateOne) Select(field string, fields ...string) *RefundUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Refund entity.
func (_u *RefundUpdateOne) Save(ctx context.Context) (*Refund, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RefundUpdateOne) SaveX(ctx context.Context) *Refund {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RefundUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RefundUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RefundUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := refund.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RefundUpdateOne) check() error {
	if v, ok := _u.mutation.RefundStatus(); ok {
		if err := refund.RefundStatusValidator(v); err != nil {
			return &ValidationError{Name: "refund_status", err: fmt.Errorf(`ent: validator failed for field "Refund.refund_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RefundReason(); ok {
		if err := refund.RefundReasonValidator(v); err != nil {
			return &ValidationError{Name: "refund_reason", err: fmt.Errorf(`ent: validator failed for field "Refund.refund_reason": %w`, err)}
		}
	}
	return nil
}

func (_u *RefundUpdateOne) sqlSave(ctx context.Context) (_node *Refund, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(refund.Table, refund.Columns, sqlgraph.NewFieldSpec(refund.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Refund.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, refund.FieldID)
		for _, f := range fields {
			if !refund.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != refund.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(refund.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(refund.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(refund.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(refund.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(refund.FieldUpdatedBy, field.TypeString)
	}
	if _u.mutation.EnvironmentIDCleared() {
		_spec.ClearField(refund.FieldEnvironmentID, field.TypeString)
	}
	if _u.mutation.PaymentIDCleared() {
		_spec.ClearField(refund.FieldPaymentID, field.TypeString)
	}
	if _u.mutation.CreditNoteIDCleared() {
		_spec.ClearField(refund.FieldCreditNoteID, field.TypeString)
	}
	if _u.mutation.PaymentGatewayCleared() {
		_spec.ClearField(refund.FieldPaymentGateway, field.TypeString)
	}
	if value, ok := _u.mutation.GatewayRefundID(); ok {
		_spec.SetField(refund.FieldGatewayRefundID, field.TypeString, value)
	}
	if _u.mutation.GatewayRefundIDCleared() {
		_spec.ClearField(refund.FieldGatewayRefundID, field.TypeString)
	}
	if value, ok := _u.mutation.GatewayTrackingID(); ok {
		_spec.SetField(refund.FieldGatewayTrackingID, field.TypeString, value)
	}
	if _u.mutation.GatewayTrackingIDCleared() {
		_spec.ClearField(refund.FieldGatewayTrackingID, field.TypeString)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(refund.FieldAmount, field.TypeOther, value)
	}
	if value, ok := _u.mutation.SettledAmount(); ok {
		_spec.SetField(refund.FieldSettledAmount, field.TypeOther, value)
	}
	if value, ok := _u.mutation.RefundStatus(); ok {
		_spec.SetField(refund.FieldRefundStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefundReason(); ok {
		_spec.SetField(refund.FieldRefundReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefundDestination(); ok {
		_spec.SetField(refund.FieldRefundDestination, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefundDestinationID(); ok {
		_spec.SetField(refund.FieldRefundDestinationID, field.TypeString, value)
	}
	if _u.mutation.RefundDestinationIDCleared() {
		_spec.ClearField(refund.FieldRefundDestinationID, field.TypeString)
	}
	if value, ok := _u.mutation.Attempt(); ok {
		_spec.SetField(refund.FieldAttempt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempt(); ok {
		_spec.AddField(refund.FieldAttempt, field.TypeInt, value)
	}
	if _u.mutation.GatewayIdempotencyTokenCleared() {
		_spec.ClearField(refund.FieldGatewayIdempotencyToken, field.TypeString)
	}
	if value, ok := _u.mutation.FailureReason(); ok {
		_spec.SetField(refund.FieldFailureReason, field.TypeString, value)
	}
	if _u.mutation.FailureReasonCleared() {
		_spec.ClearField(refund.FieldFailureReason, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(refund.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(refund.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.GatewayMetadata(); ok {
		_spec.SetField(refund.FieldGatewayMetadata, field.TypeJSON, value)
	}
	if _u.mutation.GatewayMetadataCleared() {
		_spec.ClearField(refund.FieldGatewayMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.InitiatedAt(); ok {
		_spec.SetField(refund.FieldInitiatedAt, field.TypeTime, value)
	}
	if _u.mutation.InitiatedAtCleared() {
		_spec.ClearField(refund.FieldInitiatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SucceededAt(); ok {
		_spec.SetField(refund.FieldSucceededAt, field.TypeTime, value)
	}
	if _u.mutation.SucceededAtCleared() {
		_spec.ClearField(refund.FieldSucceededAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FailedAt(); ok {
		_spec.SetField(refund.FieldFailedAt, field.TypeTime, value)
	}
	if _u.mutation.FailedAtCleared() {
		_spec.ClearField(refund.FieldFailedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CancelledAt(); ok {
		_spec.SetField(refund.FieldCancelledAt, field.TypeTime, value)
	}
	if _u.mutation.CancelledAtCleared() {
		_spec.ClearField(refund.FieldCancelledAt, field.TypeTime)
	}
	_node = &Refund{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{refund.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
