// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/couponapplication"
	"github.com/flexprice/flexprice/ent/couponassociation"
	"github.com/flexprice/flexprice/ent/creditgrant"
	"github.com/flexprice/flexprice/ent/customer"
	"github.com/flexprice/flexprice/ent/subscription"
	"github.com/flexprice/flexprice/ent/subscriptionlineitem"
	"github.com/flexprice/flexprice/ent/subscriptionpause"
	"github.com/flexprice/flexprice/ent/subscriptionphase"
	"github.com/flexprice/flexprice/ent/subscriptionschedule"
	"github.com/flexprice/flexprice/internal/types"
	"github.com/shopspring/decimal"
)

// SubscriptionCreate is the builder for creating a Subscription entity.
type SubscriptionCreate struct {
	config
	mutation *SubscriptionMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *SubscriptionCreate) SetTenantID(v string) *SubscriptionCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *SubscriptionCreate) SetStatus(v string) *SubscriptionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableStatus(v *string) *SubscriptionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SubscriptionCreate) SetCreatedAt(v time.Time) *SubscriptionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableCreatedAt(v *time.Time) *SubscriptionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SubscriptionCreate) SetUpdatedAt(v time.Time) *SubscriptionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableUpdatedAt(v *time.Time) *SubscriptionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *SubscriptionCreate) SetCreatedBy(v string) *SubscriptionCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableCreatedBy(v *string) *SubscriptionCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *SubscriptionCreate) SetUpdatedBy(v string) *SubscriptionCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableUpdatedBy(v *string) *SubscriptionCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetEnvironmentID sets the "environment_id" field.
func (_c *SubscriptionCreate) SetEnvironmentID(v string) *SubscriptionCreate {
	_c.mutation.SetEnvironmentID(v)
	return _c
}

// SetNillableEnvironmentID sets the "environment_id" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableEnvironmentID(v *string) *SubscriptionCreate {
	if v != nil {
		_c.SetEnvironmentID(*v)
	}
	return _c
}

// SetLookupKey sets the "lookup_key" field.
func (_c *SubscriptionCreate) SetLookupKey(v string) *SubscriptionCreate {
	_c.mutation.SetLookupKey(v)
	return _c
}

// SetNillableLookupKey sets the "lookup_key" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableLookupKey(v *string) *SubscriptionCreate {
	if v != nil {
		_c.SetLookupKey(*v)
	}
	return _c
}

// SetCustomerID sets the "customer_id" field.
func (_c *SubscriptionCreate) SetCustomerID(v string) *SubscriptionCreate {
	_c.mutation.SetCustomerID(v)
	return _c
}

// SetPlanID sets the "plan_id" field.
func (_c *SubscriptionCreate) SetPlanID(v string) *SubscriptionCreate {
	_c.mutation.SetPlanID(v)
	return _c
}

// SetSubscriptionStatus sets the "subscription_status" field.
func (_c *SubscriptionCreate) SetSubscriptionStatus(v types.SubscriptionStatus) *SubscriptionCreate {
	_c.mutation.SetSubscriptionStatus(v)
	return _c
}

// SetNillableSubscriptionStatus sets the "subscription_status" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableSubscriptionStatus(v *types.SubscriptionStatus) *SubscriptionCreate {
	if v != nil {
		_c.SetSubscriptionStatus(*v)
	}
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *SubscriptionCreate) SetCurrency(v string) *SubscriptionCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetBillingAnchor sets the "billing_anchor" field.
func (_c *SubscriptionCreate) SetBillingAnchor(v time.Time) *SubscriptionCreate {
	_c.mutation.SetBillingAnchor(v)
	return _c
}

// SetNillableBillingAnchor sets the "billing_anchor" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableBillingAnchor(v *time.Time) *SubscriptionCreate {
	if v != nil {
		_c.SetBillingAnchor(*v)
	}
	return _c
}

// SetStartDate sets the "start_date" field.
func (_c *SubscriptionCreate) SetStartDate(v time.Time) *SubscriptionCreate {
	_c.mutation.SetStartDate(v)
	return _c
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableStartDate(v *time.Time) *SubscriptionCreate {
	if v != nil {
		_c.SetStartDate(*v)
	}
	return _c
}

// SetEndDate sets the "end_date" field.
func (_c *SubscriptionCreate) SetEndDate(v time.Time) *SubscriptionCreate {
	_c.mutation.SetEndDate(v)
	return _c
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableEndDate(v *time.Time) *SubscriptionCreate {
	if v != nil {
		_c.SetEndDate(*v)
	}
	return _c
}

// SetCurrentPeriodStart sets the "current_period_start" field.
func (_c *SubscriptionCreate) SetCurrentPeriodStart(v time.Time) *SubscriptionCreate {
	_c.mutation.SetCurrentPeriodStart(v)
	return _c
}

// SetNillableCurrentPeriodStart sets the "current_period_start" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableCurrentPeriodStart(v *time.Time) *SubscriptionCreate {
	if v != nil {
		_c.SetCurrentPeriodStart(*v)
	}
	return _c
}

// SetCurrentPeriodEnd sets the "current_period_end" field.
func (_c *SubscriptionCreate) SetCurrentPeriodEnd(v time.Time) *SubscriptionCreate {
	_c.mutation.SetCurrentPeriodEnd(v)
	return _c
}

// SetNillableCurrentPeriodEnd sets the "current_period_end" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableCurrentPeriodEnd(v *time.Time) *SubscriptionCreate {
	if v != nil {
		_c.SetCurrentPeriodEnd(*v)
	}
	return _c
}

// SetCancelledAt sets the "cancelled_at" field.
func (_c *SubscriptionCreate) SetCancelledAt(v time.Time) *SubscriptionCreate {
	_c.mutation.SetCancelledAt(v)
	return _c
}

// SetNillableCancelledAt sets the "cancelled_at" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableCancelledAt(v *time.Time) *SubscriptionCreate {
	if v != nil {
		_c.SetCancelledAt(*v)
	}
	return _c
}

// SetCancelAt sets the "cancel_at" field.
func (_c *SubscriptionCreate) SetCancelAt(v time.Time) *SubscriptionCreate {
	_c.mutation.SetCancelAt(v)
	return _c
}

// SetNillableCancelAt sets the "cancel_at" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableCancelAt(v *time.Time) *SubscriptionCreate {
	if v != nil {
		_c.SetCancelAt(*v)
	}
	return _c
}

// SetCancelAtPeriodEnd sets the "cancel_at_period_end" field.
func (_c *SubscriptionCreate) SetCancelAtPeriodEnd(v bool) *SubscriptionCreate {
	_c.mutation.SetCancelAtPeriodEnd(v)
	return _c
}

// SetNillableCancelAtPeriodEnd sets the "cancel_at_period_end" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableCancelAtPeriodEnd(v *bool) *SubscriptionCreate {
	if v != nil {
		_c.SetCancelAtPeriodEnd(*v)
	}
	return _c
}

// SetTrialStart sets the "trial_start" field.
func (_c *SubscriptionCreate) SetTrialStart(v time.Time) *SubscriptionCreate {
	_c.mutation.SetTrialStart(v)
	return _c
}

// SetNillableTrialStart sets the "trial_start" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableTrialStart(v *time.Time) *SubscriptionCreate {
	if v != nil {
		_c.SetTrialStart(*v)
	}
	return _c
}

// SetTrialEnd sets the "trial_end" field.
func (_c *SubscriptionCreate) SetTrialEnd(v time.Time) *SubscriptionCreate {
	_c.mutation.SetTrialEnd(v)
	return _c
}

// SetNillableTrialEnd sets the "trial_end" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableTrialEnd(v *time.Time) *SubscriptionCreate {
	if v != nil {
		_c.SetTrialEnd(*v)
	}
	return _c
}

// SetBillingCadence sets the "billing_cadence" field.
func (_c *SubscriptionCreate) SetBillingCadence(v types.BillingCadence) *SubscriptionCreate {
	_c.mutation.SetBillingCadence(v)
	return _c
}

// SetBillingPeriod sets the "billing_period" field.
func (_c *SubscriptionCreate) SetBillingPeriod(v types.BillingPeriod) *SubscriptionCreate {
	_c.mutation.SetBillingPeriod(v)
	return _c
}

// SetBillingPeriodCount sets the "billing_period_count" field.
func (_c *SubscriptionCreate) SetBillingPeriodCount(v int) *SubscriptionCreate {
	_c.mutation.SetBillingPeriodCount(v)
	return _c
}

// SetNillableBillingPeriodCount sets the "billing_period_count" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableBillingPeriodCount(v *int) *SubscriptionCreate {
	if v != nil {
		_c.SetBillingPeriodCount(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *SubscriptionCreate) SetVersion(v int) *SubscriptionCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableVersion(v *int) *SubscriptionCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *SubscriptionCreate) SetMetadata(v map[string]string) *SubscriptionCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetPauseStatus sets the "pause_status" field.
func (_c *SubscriptionCreate) SetPauseStatus(v types.PauseStatus) *SubscriptionCreate {
	_c.mutation.SetPauseStatus(v)
	return _c
}

// SetNillablePauseStatus sets the "pause_status" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillablePauseStatus(v *types.PauseStatus) *SubscriptionCreate {
	if v != nil {
		_c.SetPauseStatus(*v)
	}
	return _c
}

// SetActivePauseID sets the "active_pause_id" field.
func (_c *SubscriptionCreate) SetActivePauseID(v string) *SubscriptionCreate {
	_c.mutation.SetActivePauseID(v)
	return _c
}

// SetNillableActivePauseID sets the "active_pause_id" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableActivePauseID(v *string) *SubscriptionCreate {
	if v != nil {
		_c.SetActivePauseID(*v)
	}
	return _c
}

// SetBillingCycle sets the "billing_cycle" field.
func (_c *SubscriptionCreate) SetBillingCycle(v types.BillingCycle) *SubscriptionCreate {
	_c.mutation.SetBillingCycle(v)
	return _c
}

// SetNillableBillingCycle sets the "billing_cycle" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableBillingCycle(v *types.BillingCycle) *SubscriptionCreate {
	if v != nil {
		_c.SetBillingCycle(*v)
	}
	return _c
}

// SetCommitmentAmount sets the "commitment_amount" field.
func (_c *SubscriptionCreate) SetCommitmentAmount(v decimal.Decimal) *SubscriptionCreate {
	_c.mutation.SetCommitmentAmount(v)
	return _c
}

// SetNillableCommitmentAmount sets the "commitment_amount" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableCommitmentAmount(v *decimal.Decimal) *SubscriptionCreate {
	if v != nil {
		_c.SetCommitmentAmount(*v)
	}
	return _c
}

// SetCommitmentDuration sets the "commitment_duration" field.
func (_c *SubscriptionCreate) SetCommitmentDuration(v types.BillingPeriod) *SubscriptionCreate {
	_c.mutation.SetCommitmentDuration(v)
	return _c
}

// SetNillableCommitmentDuration sets the "commitment_duration" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableCommitmentDuration(v *types.BillingPeriod) *SubscriptionCreate {
	if v != nil {
		_c.SetCommitmentDuration(*v)
	}
	return _c
}

// SetOverageFactor sets the "overage_factor" field.
func (_c *SubscriptionCreate) SetOverageFactor(v decimal.Decimal) *SubscriptionCreate {
	_c.mutation.SetOverageFactor(v)
	return _c
}

// SetNillableOverageFactor sets the "overage_factor" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableOverageFactor(v *decimal.Decimal) *SubscriptionCreate {
	if v != nil {
		_c.SetOverageFactor(*v)
	}
	return _c
}

// SetPaymentBehavior sets the "payment_behavior" field.
func (_c *SubscriptionCreate) SetPaymentBehavior(v types.PaymentBehavior) *SubscriptionCreate {
	_c.mutation.SetPaymentBehavior(v)
	return _c
}

// SetNillablePaymentBehavior sets the "payment_behavior" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillablePaymentBehavior(v *types.PaymentBehavior) *SubscriptionCreate {
	if v != nil {
		_c.SetPaymentBehavior(*v)
	}
	return _c
}

// SetCollectionMethod sets the "collection_method" field.
func (_c *SubscriptionCreate) SetCollectionMethod(v types.CollectionMethod) *SubscriptionCreate {
	_c.mutation.SetCollectionMethod(v)
	return _c
}

// SetNillableCollectionMethod sets the "collection_method" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableCollectionMethod(v *types.CollectionMethod) *SubscriptionCreate {
	if v != nil {
		_c.SetCollectionMethod(*v)
	}
	return _c
}

// SetGatewayPaymentMethodID sets the "gateway_payment_method_id" field.
func (_c *SubscriptionCreate) SetGatewayPaymentMethodID(v string) *SubscriptionCreate {
	_c.mutation.SetGatewayPaymentMethodID(v)
	return _c
}

// SetNillableGatewayPaymentMethodID sets the "gateway_payment_method_id" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableGatewayPaymentMethodID(v *string) *SubscriptionCreate {
	if v != nil {
		_c.SetGatewayPaymentMethodID(*v)
	}
	return _c
}

// SetTimezone sets the "timezone" field.
func (_c *SubscriptionCreate) SetTimezone(v string) *SubscriptionCreate {
	_c.mutation.SetTimezone(v)
	return _c
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableTimezone(v *string) *SubscriptionCreate {
	if v != nil {
		_c.SetTimezone(*v)
	}
	return _c
}

// SetProrationBehavior sets the "proration_behavior" field.
func (_c *SubscriptionCreate) SetProrationBehavior(v types.ProrationBehavior) *SubscriptionCreate {
	_c.mutation.SetProrationBehavior(v)
	return _c
}

// SetNillableProrationBehavior sets the "proration_behavior" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableProrationBehavior(v *types.ProrationBehavior) *SubscriptionCreate {
	if v != nil {
		_c.SetProrationBehavior(*v)
	}
	return _c
}

// SetLineItemGrouping sets the "line_item_grouping" field.
func (_c *SubscriptionCreate) SetLineItemGrouping(v types.LineItemGrouping) *SubscriptionCreate {
	_c.mutation.SetLineItemGrouping(v)
	return _c
}

// SetNillableLineItemGrouping sets the "line_item_grouping" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableLineItemGrouping(v *types.LineItemGrouping) *SubscriptionCreate {
	if v != nil {
		_c.SetLineItemGrouping(*v)
	}
	return _c
}

// SetEnableTrueUp sets the "enable_true_up" field.
func (_c *SubscriptionCreate) SetEnableTrueUp(v bool) *SubscriptionCreate {
	_c.mutation.SetEnableTrueUp(v)
	return _c
}

// SetNillableEnableTrueUp sets the "enable_true_up" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableEnableTrueUp(v *bool) *SubscriptionCreate {
	if v != nil {
		_c.SetEnableTrueUp(*v)
	}
	return _c
}

// SetInvoicingCustomerID sets the "invoicing_customer_id" field.
func (_c *SubscriptionCreate) SetInvoicingCustomerID(v string) *SubscriptionCreate {
	_c.mutation.SetInvoicingCustomerID(v)
	return _c
}

// SetNillableInvoicingCustomerID sets the "invoicing_customer_id" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableInvoicingCustomerID(v *string) *SubscriptionCreate {
	if v != nil {
		_c.SetInvoicingCustomerID(*v)
	}
	return _c
}

// SetParentSubscriptionID sets the "parent_subscription_id" field.
func (_c *SubscriptionCreate) SetParentSubscriptionID(v string) *SubscriptionCreate {
	_c.mutation.SetParentSubscriptionID(v)
	return _c
}

// SetNillableParentSubscriptionID sets the "parent_subscription_id" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableParentSubscriptionID(v *string) *SubscriptionCreate {
	if v != nil {
		_c.SetParentSubscriptionID(*v)
	}
	return _c
}

// SetPaymentTerms sets the "payment_terms" field.
func (_c *SubscriptionCreate) SetPaymentTerms(v types.PaymentTerms) *SubscriptionCreate {
	_c.mutation.SetPaymentTerms(v)
	return _c
}

// SetNillablePaymentTerms sets the "payment_terms" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillablePaymentTerms(v *types.PaymentTerms) *SubscriptionCreate {
	if v != nil {
		_c.SetPaymentTerms(*v)
	}
	return _c
}

// SetSubscriptionType sets the "subscription_type" field.
func (_c *SubscriptionCreate) SetSubscriptionType(v types.SubscriptionType) *SubscriptionCreate {
	_c.mutation.SetSubscriptionType(v)
	return _c
}

// SetNillableSubscriptionType sets the "subscription_type" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableSubscriptionType(v *types.SubscriptionType) *SubscriptionCreate {
	if v != nil {
		_c.SetSubscriptionType(*v)
	}
	return _c
}

// SetAutoInvoiceThreshold sets the "auto_invoice_threshold" field.
func (_c *SubscriptionCreate) SetAutoInvoiceThreshold(v decimal.Decimal) *SubscriptionCreate {
	_c.mutation.SetAutoInvoiceThreshold(v)
	return _c
}

// SetNillableAutoInvoiceThreshold sets the "auto_invoice_threshold" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableAutoInvoiceThreshold(v *decimal.Decimal) *SubscriptionCreate {
	if v != nil {
		_c.SetAutoInvoiceThreshold(*v)
	}
	return _c
}

// SetSyncedPriceSequence sets the "synced_price_sequence" field.
func (_c *SubscriptionCreate) SetSyncedPriceSequence(v int64) *SubscriptionCreate {
	_c.mutation.SetSyncedPriceSequence(v)
	return _c
}

// SetNillableSyncedPriceSequence sets the "synced_price_sequence" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableSyncedPriceSequence(v *int64) *SubscriptionCreate {
	if v != nil {
		_c.SetSyncedPriceSequence(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SubscriptionCreate) SetID(v string) *SubscriptionCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddLineItemIDs adds the "line_items" edge to the SubscriptionLineItem entity by IDs.
func (_c *SubscriptionCreate) AddLineItemIDs(ids ...string) *SubscriptionCreate {
	_c.mutation.AddLineItemIDs(ids...)
	return _c
}

// AddLineItems adds the "line_items" edges to the SubscriptionLineItem entity.
func (_c *SubscriptionCreate) AddLineItems(v ...*SubscriptionLineItem) *SubscriptionCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLineItemIDs(ids...)
}

// AddPauseIDs adds the "pauses" edge to the SubscriptionPause entity by IDs.
func (_c *SubscriptionCreate) AddPauseIDs(ids ...string) *SubscriptionCreate {
	_c.mutation.AddPauseIDs(ids...)
	return _c
}

// AddPauses adds the "pauses" edges to the SubscriptionPause entity.
func (_c *SubscriptionCreate) AddPauses(v ...*SubscriptionPause) *SubscriptionCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPauseIDs(ids...)
}

// AddPhaseIDs adds the "phases" edge to the SubscriptionPhase entity by IDs.
func (_c *SubscriptionCreate) AddPhaseIDs(ids ...string) *SubscriptionCreate {
	_c.mutation.AddPhaseIDs(ids...)
	return _c
}

// AddPhases adds the "phases" edges to the SubscriptionPhase entity.
func (_c *SubscriptionCreate) AddPhases(v ...*SubscriptionPhase) *SubscriptionCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPhaseIDs(ids...)
}

// AddScheduleIDs adds the "schedules" edge to the SubscriptionSchedule entity by IDs.
func (_c *SubscriptionCreate) AddScheduleIDs(ids ...string) *SubscriptionCreate {
	_c.mutation.AddScheduleIDs(ids...)
	return _c
}

// AddSchedules adds the "schedules" edges to the SubscriptionSchedule entity.
func (_c *SubscriptionCreate) AddSchedules(v ...*SubscriptionSchedule) *SubscriptionCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddScheduleIDs(ids...)
}

// AddCreditGrantIDs adds the "credit_grants" edge to the CreditGrant entity by IDs.
func (_c *SubscriptionCreate) AddCreditGrantIDs(ids ...string) *SubscriptionCreate {
	_c.mutation.AddCreditGrantIDs(ids...)
	return _c
}

// AddCreditGrants adds the "credit_grants" edges to the CreditGrant entity.
func (_c *SubscriptionCreate) AddCreditGrants(v ...*CreditGrant) *SubscriptionCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCreditGrantIDs(ids...)
}

// AddCouponAssociationIDs adds the "coupon_associations" edge to the CouponAssociation entity by IDs.
func (_c *SubscriptionCreate) AddCouponAssociationIDs(ids ...string) *SubscriptionCreate {
	_c.mutation.AddCouponAssociationIDs(ids...)
	return _c
}

// AddCouponAssociations adds the "coupon_associations" edges to the CouponAssociation entity.
func (_c *SubscriptionCreate) AddCouponAssociations(v ...*CouponAssociation) *SubscriptionCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCouponAssociationIDs(ids...)
}

// AddCouponApplicationIDs adds the "coupon_applications" edge to the CouponApplication entity by IDs.
func (_c *SubscriptionCreate) AddCouponApplicationIDs(ids ...string) *SubscriptionCreate {
	_c.mutation.AddCouponApplicationIDs(ids...)
	return _c
}

// AddCouponApplications adds the "coupon_applications" edges to the CouponApplication entity.
func (_c *SubscriptionCreate) AddCouponApplications(v ...*CouponApplication) *SubscriptionCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCouponApplicationIDs(ids...)
}

// SetInvoicingCustomer sets the "invoicing_customer" edge to the Customer entity.
func (_c *SubscriptionCreate) SetInvoicingCustomer(v *Customer) *SubscriptionCreate {
	return _c.SetInvoicingCustomerID(v.ID)
}

// Mutation returns the SubscriptionMutation object of the builder.
func (_c *SubscriptionCreate) Mutation() *SubscriptionMutation {
	return _c.mutation
}

// Save creates the Subscription in the database.
func (_c *SubscriptionCreate) Save(ctx context.Context) (*Subscription, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubscriptionCreate) SaveX(ctx context.Context) *Subscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SubscriptionCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := subscription.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := subscription.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := subscription.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.EnvironmentID(); !ok {
		v := subscription.DefaultEnvironmentID
		_c.mutation.SetEnvironmentID(v)
	}
	if _, ok := _c.mutation.SubscriptionStatus(); !ok {
		v := subscription.DefaultSubscriptionStatus
		_c.mutation.SetSubscriptionStatus(v)
	}
	if _, ok := _c.mutation.BillingAnchor(); !ok {
		v := subscription.DefaultBillingAnchor()
		_c.mutation.SetBillingAnchor(v)
	}
	if _, ok := _c.mutation.StartDate(); !ok {
		v := subscription.DefaultStartDate()
		_c.mutation.SetStartDate(v)
	}
	if _, ok := _c.mutation.CurrentPeriodStart(); !ok {
		v := subscription.DefaultCurrentPeriodStart()
		_c.mutation.SetCurrentPeriodStart(v)
	}
	if _, ok := _c.mutation.CurrentPeriodEnd(); !ok {
		v := subscription.DefaultCurrentPeriodEnd()
		_c.mutation.SetCurrentPeriodEnd(v)
	}
	if _, ok := _c.mutation.CancelAtPeriodEnd(); !ok {
		v := subscription.DefaultCancelAtPeriodEnd
		_c.mutation.SetCancelAtPeriodEnd(v)
	}
	if _, ok := _c.mutation.BillingPeriodCount(); !ok {
		v := subscription.DefaultBillingPeriodCount
		_c.mutation.SetBillingPeriodCount(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := subscription.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.PauseStatus(); !ok {
		v := subscription.DefaultPauseStatus
		_c.mutation.SetPauseStatus(v)
	}
	if _, ok := _c.mutation.BillingCycle(); !ok {
		v := subscription.DefaultBillingCycle
		_c.mutation.SetBillingCycle(v)
	}
	if _, ok := _c.mutation.OverageFactor(); !ok {
		v := subscription.DefaultOverageFactor
		_c.mutation.SetOverageFactor(v)
	}
	if _, ok := _c.mutation.PaymentBehavior(); !ok {
		v := subscription.DefaultPaymentBehavior
		_c.mutation.SetPaymentBehavior(v)
	}
	if _, ok := _c.mutation.CollectionMethod(); !ok {
		v := subscription.DefaultCollectionMethod
		_c.mutation.SetCollectionMethod(v)
	}
	if _, ok := _c.mutation.Timezone(); !ok {
		v := subscription.DefaultTimezone
		_c.mutation.SetTimezone(v)
	}
	if _, ok := _c.mutation.ProrationBehavior(); !ok {
		v := subscription.DefaultProrationBehavior
		_c.mutation.SetProrationBehavior(v)
	}
	if _, ok := _c.mutation.LineItemGrouping(); !ok {
		v := subscription.DefaultLineItemGrouping
		_c.mutation.SetLineItemGrouping(v)
	}
	if _, ok := _c.mutation.EnableTrueUp(); !ok {
		v := subscription.DefaultEnableTrueUp
		_c.mutation.SetEnableTrueUp(v)
	}
	if _, ok := _c.mutation.SubscriptionType(); !ok {
		v := subscription.DefaultSubscriptionType
		_c.mutation.SetSubscriptionType(v)
	}
	if _, ok := _c.mutation.SyncedPriceSequence(); !ok {
		v := subscription.DefaultSyncedPriceSequence
		_c.mutation.SetSyncedPriceSequence(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubscriptionCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Subscription.tenant_id"`)}
	}
	if v, ok := _c.mutation.TenantID(); ok {
		if err := subscription.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "Subscription.tenant_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Subscription.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Subscription.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Subscription.updated_at"`)}
	}
	if _, ok := _c.mutation.CustomerID(); !ok {
		return &ValidationError{Name: "customer_id", err: errors.New(`ent: missing required field "Subscription.customer_id"`)}
	}
	if v, ok := _c.mutation.CustomerID(); ok {
		if err := subscription.CustomerIDValidator(v); err != nil {
			return &ValidationError{Name: "customer_id", err: fmt.Errorf(`ent: validator failed for field "Subscription.customer_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PlanID(); !ok {
		return &ValidationError{Name: "plan_id", err: errors.New(`ent: missing required field "Subscription.plan_id"`)}
	}
	if v, ok := _c.mutation.PlanID(); ok {
		if err := subscription.PlanIDValidator(v); err != nil {
			return &ValidationError{Name: "plan_id", err: fmt.Errorf(`ent: validator failed for field "Subscription.plan_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SubscriptionStatus(); !ok {
		return &ValidationError{Name: "subscription_status", err: errors.New(`ent: missing required field "Subscription.subscription_status"`)}
	}
	if v, ok := _c.mutation.SubscriptionStatus(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "subscription_status", err: fmt.Errorf(`ent: validator failed for field "Subscription.subscription_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "Subscription.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := subscription.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "Subscription.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BillingAnchor(); !ok {
		return &ValidationError{Name: "billing_anchor", err: errors.New(`ent: missing required field "Subscription.billing_anchor"`)}
	}
	if _, ok := _c.mutation.StartDate(); !ok {
		return &ValidationError{Name: "start_date", err: errors.New(`ent: missing required field "Subscription.start_date"`)}
	}
	if _, ok := _c.mutation.CurrentPeriodStart(); !ok {
		return &ValidationError{Name: "current_period_start", err: errors.New(`ent: missing required field "Subscription.current_period_start"`)}
	}
	if _, ok := _c.mutation.CurrentPeriodEnd(); !ok {
		return &ValidationError{Name: "current_period_end", err: errors.New(`ent: missing required field "Subscription.current_period_end"`)}
	}
	if _, ok := _c.mutation.CancelAtPeriodEnd(); !ok {
		return &ValidationError{Name: "cancel_at_period_end", err: errors.New(`ent: missing required field "Subscription.cancel_at_period_end"`)}
	}
	if _, ok := _c.mutation.BillingCadence(); !ok {
		return &ValidationError{Name: "billing_cadence", err: errors.New(`ent: missing required field "Subscription.billing_cadence"`)}
	}
	if v, ok := _c.mutation.BillingCadence(); ok {
		if err := subscription.BillingCadenceValidator(string(v)); err != nil {
			return &ValidationError{Name: "billing_cadence", err: fmt.Errorf(`ent: validator failed for field "Subscription.billing_cadence": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BillingPeriod(); !ok {
		return &ValidationError{Name: "billing_period", err: errors.New(`ent: missing required field "Subscription.billing_period"`)}
	}
	if v, ok := _c.mutation.BillingPeriod(); ok {
		if err := subscription.BillingPeriodValidator(string(v)); err != nil {
			return &ValidationError{Name: "billing_period", err: fmt.Errorf(`ent: validator failed for field "Subscription.billing_period": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BillingPeriodCount(); !ok {
		return &ValidationError{Name: "billing_period_count", err: errors.New(`ent: missing required field "Subscription.billing_period_count"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "Subscription.version"`)}
	}
	if _, ok := _c.mutation.PauseStatus(); !ok {
		return &ValidationError{Name: "pause_status", err: errors.New(`ent: missing required field "Subscription.pause_status"`)}
	}
	if v, ok := _c.mutation.PauseStatus(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "pause_status", err: fmt.Errorf(`ent: validator failed for field "Subscription.pause_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BillingCycle(); !ok {
		return &ValidationError{Name: "billing_cycle", err: errors.New(`ent: missing required field "Subscription.billing_cycle"`)}
	}
	if v, ok := _c.mutation.BillingCycle(); ok {
		if err := subscription.BillingCycleValidator(string(v)); err != nil {
			return &ValidationError{Name: "billing_cycle", err: fmt.Errorf(`ent: validator failed for field "Subscription.billing_cycle": %w`, err)}
		}
	}
	if v, ok := _c.mutation.CommitmentDuration(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "commitment_duration", err: fmt.Errorf(`ent: validator failed for field "Subscription.commitment_duration": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PaymentBehavior(); !ok {
		return &ValidationError{Name: "payment_behavior", err: errors.New(`ent: missing required field "Subscription.payment_behavior"`)}
	}
	if v, ok := _c.mutation.PaymentBehavior(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "payment_behavior", err: fmt.Errorf(`ent: validator failed for field "Subscription.payment_behavior": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CollectionMethod(); !ok {
		return &ValidationError{Name: "collection_method", err: errors.New(`ent: missing required field "Subscription.collection_method"`)}
	}
	if v, ok := _c.mutation.CollectionMethod(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "collection_method", err: fmt.Errorf(`ent: validator failed for field "Subscription.collection_method": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Timezone(); !ok {
		return &ValidationError{Name: "timezone", err: errors.New(`ent: missing required field "Subscription.timezone"`)}
	}
	if _, ok := _c.mutation.ProrationBehavior(); !ok {
		return &ValidationError{Name: "proration_behavior", err: errors.New(`ent: missing required field "Subscription.proration_behavior"`)}
	}
	if v, ok := _c.mutation.ProrationBehavior(); ok {
		if err := subscription.ProrationBehaviorValidator(string(v)); err != nil {
			return &ValidationError{Name: "proration_behavior", err: fmt.Errorf(`ent: validator failed for field "Subscription.proration_behavior": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LineItemGrouping(); !ok {
		return &ValidationError{Name: "line_item_grouping", err: errors.New(`ent: missing required field "Subscription.line_item_grouping"`)}
	}
	if v, ok := _c.mutation.LineItemGrouping(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "line_item_grouping", err: fmt.Errorf(`ent: validator failed for field "Subscription.line_item_grouping": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EnableTrueUp(); !ok {
		return &ValidationError{Name: "enable_true_up", err: errors.New(`ent: missing required field "Subscription.enable_true_up"`)}
	}
	if v, ok := _c.mutation.PaymentTerms(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "payment_terms", err: fmt.Errorf(`ent: validator failed for field "Subscription.payment_terms": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SubscriptionType(); !ok {
		return &ValidationError{Name: "subscription_type", err: errors.New(`ent: missing required field "Subscription.subscription_type"`)}
	}
	if v, ok := _c.mutation.SubscriptionType(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "subscription_type", err: fmt.Errorf(`ent: validator failed for field "Subscription.subscription_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SyncedPriceSequence(); !ok {
		return &ValidationError{Name: "synced_price_sequence", err: errors.New(`ent: missing required field "Subscription.synced_price_sequence"`)}
	}
	return nil
}

func (_c *SubscriptionCreate) sqlSave(ctx context.Context) (*Subscription, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Subscription.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SubscriptionCreate) createSpec() (*Subscription, *sqlgraph.CreateSpec) {
	var (
		_node = &Subscription{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(subscription.Table, sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(subscription.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(subscription.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(subscription.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(subscription.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(subscription.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(subscription.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	if value, ok := _c.mutation.EnvironmentID(); ok {
		_spec.SetField(subscription.FieldEnvironmentID, field.TypeString, value)
		_node.EnvironmentID = value
	}
	if value, ok := _c.mutation.LookupKey(); ok {
		_spec.SetField(subscription.FieldLookupKey, field.TypeString, value)
		_node.LookupKey = value
	}
	if value, ok := _c.mutation.CustomerID(); ok {
		_spec.SetField(subscription.FieldCustomerID, field.TypeString, value)
		_node.CustomerID = value
	}
	if value, ok := _c.mutation.PlanID(); ok {
		_spec.SetField(subscription.FieldPlanID, field.TypeString, value)
		_node.PlanID = value
	}
	if value, ok := _c.mutation.SubscriptionStatus(); ok {
		_spec.SetField(subscription.FieldSubscriptionStatus, field.TypeString, value)
		_node.SubscriptionStatus = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(subscription.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.BillingAnchor(); ok {
		_spec.SetField(subscription.FieldBillingAnchor, field.TypeTime, value)
		_node.BillingAnchor = value
	}
	if value, ok := _c.mutation.StartDate(); ok {
		_spec.SetField(subscription.FieldStartDate, field.TypeTime, value)
		_node.StartDate = value
	}
	if value, ok := _c.mutation.EndDate(); ok {
		_spec.SetField(subscription.FieldEndDate, field.TypeTime, value)
		_node.EndDate = &value
	}
	if value, ok := _c.mutation.CurrentPeriodStart(); ok {
		_spec.SetField(subscription.FieldCurrentPeriodStart, field.TypeTime, value)
		_node.CurrentPeriodStart = value
	}
	if value, ok := _c.mutation.CurrentPeriodEnd(); ok {
		_spec.SetField(subscription.FieldCurrentPeriodEnd, field.TypeTime, value)
		_node.CurrentPeriodEnd = value
	}
	if value, ok := _c.mutation.CancelledAt(); ok {
		_spec.SetField(subscription.FieldCancelledAt, field.TypeTime, value)
		_node.CancelledAt = &value
	}
	if value, ok := _c.mutation.CancelAt(); ok {
		_spec.SetField(subscription.FieldCancelAt, field.TypeTime, value)
		_node.CancelAt = &value
	}
	if value, ok := _c.mutation.CancelAtPeriodEnd(); ok {
		_spec.SetField(subscription.FieldCancelAtPeriodEnd, field.TypeBool, value)
		_node.CancelAtPeriodEnd = value
	}
	if value, ok := _c.mutation.TrialStart(); ok {
		_spec.SetField(subscription.FieldTrialStart, field.TypeTime, value)
		_node.TrialStart = &value
	}
	if value, ok := _c.mutation.TrialEnd(); ok {
		_spec.SetField(subscription.FieldTrialEnd, field.TypeTime, value)
		_node.TrialEnd = &value
	}
	if value, ok := _c.mutation.BillingCadence(); ok {
		_spec.SetField(subscription.FieldBillingCadence, field.TypeString, value)
		_node.BillingCadence = value
	}
	if value, ok := _c.mutation.BillingPeriod(); ok {
		_spec.SetField(subscription.FieldBillingPeriod, field.TypeString, value)
		_node.BillingPeriod = value
	}
	if value, ok := _c.mutation.BillingPeriodCount(); ok {
		_spec.SetField(subscription.FieldBillingPeriodCount, field.TypeInt, value)
		_node.BillingPeriodCount = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(subscription.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(subscription.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.PauseStatus(); ok {
		_spec.SetField(subscription.FieldPauseStatus, field.TypeString, value)
		_node.PauseStatus = value
	}
	if value, ok := _c.mutation.ActivePauseID(); ok {
		_spec.SetField(subscription.FieldActivePauseID, field.TypeString, value)
		_node.ActivePauseID = &value
	}
	if value, ok := _c.mutation.BillingCycle(); ok {
		_spec.SetField(subscription.FieldBillingCycle, field.TypeString, value)
		_node.BillingCycle = value
	}
	if value, ok := _c.mutation.CommitmentAmount(); ok {
		_spec.SetField(subscription.FieldCommitmentAmount, field.TypeOther, value)
		_node.CommitmentAmount = &value
	}
	if value, ok := _c.mutation.CommitmentDuration(); ok {
		_spec.SetField(subscription.FieldCommitmentDuration, field.TypeString, value)
		_node.CommitmentDuration = &value
	}
	if value, ok := _c.mutation.OverageFactor(); ok {
		_spec.SetField(subscription.FieldOverageFactor, field.TypeOther, value)
		_node.OverageFactor = &value
	}
	if value, ok := _c.mutation.PaymentBehavior(); ok {
		_spec.SetField(subscription.FieldPaymentBehavior, field.TypeString, value)
		_node.PaymentBehavior = value
	}
	if value, ok := _c.mutation.CollectionMethod(); ok {
		_spec.SetField(subscription.FieldCollectionMethod, field.TypeString, value)
		_node.CollectionMethod = value
	}
	if value, ok := _c.mutation.GatewayPaymentMethodID(); ok {
		_spec.SetField(subscription.FieldGatewayPaymentMethodID, field.TypeString, value)
		_node.GatewayPaymentMethodID = value
	}
	if value, ok := _c.mutation.Timezone(); ok {
		_spec.SetField(subscription.FieldTimezone, field.TypeString, value)
		_node.Timezone = value
	}
	if value, ok := _c.mutation.ProrationBehavior(); ok {
		_spec.SetField(subscription.FieldProrationBehavior, field.TypeString, value)
		_node.ProrationBehavior = value
	}
	if value, ok := _c.mutation.LineItemGrouping(); ok {
		_spec.SetField(subscription.FieldLineItemGrouping, field.TypeString, value)
		_node.LineItemGrouping = value
	}
	if value, ok := _c.mutation.EnableTrueUp(); ok {
		_spec.SetField(subscription.FieldEnableTrueUp, field.TypeBool, value)
		_node.EnableTrueUp = value
	}
	if value, ok := _c.mutation.ParentSubscriptionID(); ok {
		_spec.SetField(subscription.FieldParentSubscriptionID, field.TypeString, value)
		_node.ParentSubscriptionID = &value
	}
	if value, ok := _c.mutation.PaymentTerms(); ok {
		_spec.SetField(subscription.FieldPaymentTerms, field.TypeString, value)
		_node.PaymentTerms = &value
	}
	if value, ok := _c.mutation.SubscriptionType(); ok {
		_spec.SetField(subscription.FieldSubscriptionType, field.TypeString, value)
		_node.SubscriptionType = value
	}
	if value, ok := _c.mutation.AutoInvoiceThreshold(); ok {
		_spec.SetField(subscription.FieldAutoInvoiceThreshold, field.TypeOther, value)
		_node.AutoInvoiceThreshold = &value
	}
	if value, ok := _c.mutation.SyncedPriceSequence(); ok {
		_spec.SetField(subscription.FieldSyncedPriceSequence, field.TypeInt64, value)
		_node.SyncedPriceSequence = value
	}
	if nodes := _c.mutation.LineItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.LineItemsTable,
			Columns: []string{subscription.LineItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionlineitem.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PausesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.PausesTable,
			Columns: []string{subscription.PausesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionpause.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PhasesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.PhasesTable,
			Columns: []string{subscription.PhasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionphase.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SchedulesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.SchedulesTable,
			Columns: []string{subscription.SchedulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionschedule.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CreditGrantsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.CreditGrantsTable,
			Columns: []string{subscription.CreditGrantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(creditgrant.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CouponAssociationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.CouponAssociationsTable,
			Columns: []string{subscription.CouponAssociationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(couponassociation.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CouponApplicationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.CouponApplicationsTable,
			Columns: []string{subscription.CouponApplicationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(couponapplication.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.InvoicingCustomerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subscription.InvoicingCustomerTable,
			Columns: []string{subscription.InvoicingCustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.InvoicingCustomerID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SubscriptionCreateBulk is the builder for creating many Subscription entities in bulk.
type SubscriptionCreateBulk struct {
	config
	err      error
	builders []*SubscriptionCreate
}

// Save creates the Subscription entities in the database.
func (_c *SubscriptionCreateBulk) Save(ctx context.Context) ([]*Subscription, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Subscription, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubscriptionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubscriptionCreateBulk) SaveX(ctx context.Context) []*Subscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
