// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/predicate"
	"github.com/flexprice/flexprice/ent/subscription"
	"github.com/flexprice/flexprice/ent/subscriptionphase"
)

// SubscriptionPhaseUpdate is the builder for updating SubscriptionPhase entities.
type SubscriptionPhaseUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionPhaseMutation
}

// Where appends a list predicates to the SubscriptionPhaseUpdate builder.
func (_u *SubscriptionPhaseUpdate) Where(ps ...predicate.SubscriptionPhase) *SubscriptionPhaseUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionPhaseUpdate) SetStatus(v string) *SubscriptionPhaseUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionPhaseUpdate) SetNillableStatus(v *string) *SubscriptionPhaseUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionPhaseUpdate) SetUpdatedAt(v time.Time) *SubscriptionPhaseUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *SubscriptionPhaseUpdate) SetUpdatedBy(v string) *SubscriptionPhaseUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *SubscriptionPhaseUpdate) SetNillableUpdatedBy(v *string) *SubscriptionPhaseUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *SubscriptionPhaseUpdate) ClearUpdatedBy() *SubscriptionPhaseUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *SubscriptionPhaseUpdate) SetMetadata(v map[string]string) *SubscriptionPhaseUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *SubscriptionPhaseUpdate) ClearMetadata() *SubscriptionPhaseUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *SubscriptionPhaseUpdate) SetSubscriptionID(v string) *SubscriptionPhaseUpdate {
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *SubscriptionPhaseUpdate) SetNillableSubscriptionID(v *string) *SubscriptionPhaseUpdate {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *SubscriptionPhaseUpdate) SetEndDate(v time.Time) *SubscriptionPhaseUpdate {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *SubscriptionPhaseUpdate) SetNillableEndDate(v *time.Time) *SubscriptionPhaseUpdate {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// ClearEndDate clears the value of the "end_date" field.
func (_u *SubscriptionPhaseUpdate) ClearEndDate() *SubscriptionPhaseUpdate {
	_u.mutation.ClearEndDate()
	return _u
}

// SetSubscription sets the "subscription" edge to the Subscription entity.
func (_u *SubscriptionPhaseUpdate) SetSubscription(v *Subscription) *SubscriptionPhaseUpdate {
	return _u.SetSubscriptionID(v.ID)
}

// Mutation returns the SubscriptionPhaseMutation object of the builder.
func (_u *SubscriptionPhaseUpdate) Mutation() *SubscriptionPhaseMutation {
	return _u.mutation
}

// ClearSubscription clears the "subscription" edge to the Subscription entity.
func (_u *SubscriptionPhaseUpdate) ClearSubscription() *SubscriptionPhaseUpdate {
	_u.mutation.ClearSubscription()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionPhaseUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionPhaseUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionPhaseUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionPhaseUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionPhaseUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscriptionphase.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionPhaseUpdate) check() error {
	if v, ok := _u.mutation.SubscriptionID(); ok {
		if err := subscriptionphase.SubscriptionIDValidator(v); err != nil {
			return &ValidationError{Name: "subscription_id", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPhase.subscription_id": %w`, err)}
		}
	}
	if _u.mutation.SubscriptionCleared() && len(_u.mutation.SubscriptionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionPhase.subscription"`)
	}
	return nil
}

func (_u *SubscriptionPhaseUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionphase.Table, subscriptionphase.Columns, sqlgraph.NewFieldSpec(subscriptionphase.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscriptionphase.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionphase.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(subscriptionphase.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(subscriptionphase.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(subscriptionphase.FieldUpdatedBy, field.TypeString)
	}
	if _u.mutation.EnvironmentIDCleared() {
		_spec.ClearField(subscriptionphase.FieldEnvironmentID, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(subscriptionphase.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(subscriptionphase.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(subscriptionphase.FieldEndDate, field.TypeTime, value)
	}
	if _u.mutation.EndDateCleared() {
		_spec.ClearField(subscriptionphase.FieldEndDate, field.TypeTime)
	}
	if _u.mutation.SubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionphase.SubscriptionTable,
			Columns: []string{subscriptionphase.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionphase.SubscriptionTable,
			Columns: []string{subscriptionphase.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionphase.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionPhaseUpdateOne is the builder for updating a single SubscriptionPhase entity.
type SubscriptionPhaseUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionPhaseMutation
}

// SetStatus sets the "status" field.
func (_u *SubscriptionPhaseUpdateOne) SetStatus(v string) *SubscriptionPhaseUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionPhaseUpdateOne) SetNillableStatus(v *string) *SubscriptionPhaseUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionPhaseUpdateOne) SetUpdatedAt(v time.Time) *SubscriptionPhaseUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *SubscriptionPhaseUpdateOne) SetUpdatedBy(v string) *SubscriptionPhaseUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *SubscriptionPhaseUpdateOne) SetNillableUpdatedBy(v *string) *SubscriptionPhaseUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *SubscriptionPhaseUpdateOne) ClearUpdatedBy() *SubscriptionPhaseUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *SubscriptionPhaseUpdateOne) SetMetadata(v map[string]string) *SubscriptionPhaseUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *SubscriptionPhaseUpdateOne) ClearMetadata() *SubscriptionPhaseUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *SubscriptionPhaseUpdateOne) SetSubscriptionID(v string) *SubscriptionPhaseUpdateOne {
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *SubscriptionPhaseUpdateOne) SetNillableSubscriptionID(v *string) *SubscriptionPhaseUpdateOne {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *SubscriptionPhaseUpdateOne) SetEndDate(v time.Time) *SubscriptionPhaseUpdateOne {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *SubscriptionPhaseUpdateOne) SetNillableEndDate(v *time.Time) *SubscriptionPhaseUpdateOne {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// ClearEndDate clears the value of the "end_date" field.
func (_u *SubscriptionPhaseUpdateOne) ClearEndDate() *SubscriptionPhaseUpdateOne {
	_u.mutation.ClearEndDate()
	return _u
}

// SetSubscription sets the "subscription" edge to the Subscription entity.
func (_u *SubscriptionPhaseUpdateOne) SetSubscription(v *Subscription) *SubscriptionPhaseUpdateOne {
	return _u.SetSubscriptionID(v.ID)
}

// Mutation returns the SubscriptionPhaseMutation object of the builder.
func (_u *SubscriptionPhaseUpdateOne) Mutation() *SubscriptionPhaseMutation {
	return _u.mutation
}

// ClearSubscription clears the "subscription" edge to the Subscription entity.
func (_u *SubscriptionPhaseUpdateOne) ClearSubscription() *SubscriptionPhaseUpdateOne {
	_u.mutation.ClearSubscription()
	return _u
}

// Where appends a list predicates to the SubscriptionPhaseUpdate builder.
func (_u *SubscriptionPhaseUpdateOne) Where(ps ...predicate.SubscriptionPhase) *SubscriptionPhaseUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionPhaseUpdateOne) Select(field string, fields ...string) *SubscriptionPhaseUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SubscriptionPhase entity.
func (_u *SubscriptionPhaseUpdateOne) Save(ctx context.Context) (*SubscriptionPhase, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionPhaseUpdateOne) SaveX(ctx context.Context) *SubscriptionPhase {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionPhaseUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionPhaseUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionPhaseUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscriptionphase.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionPhaseUpdateOne) check() error {
	if v, ok := _u.mutation.SubscriptionID(); ok {
		if err := subscriptionphase.SubscriptionIDValidator(v); err != nil {
			return &ValidationError{Name: "subscription_id", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPhase.subscription_id": %w`, err)}
		}
	}
	if _u.mutation.SubscriptionCleared() && len(_u.mutation.SubscriptionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionPhase.subscription"`)
	}
	return nil
}

func (_u *SubscriptionPhaseUpdateOne) sqlSave(ctx context.Context) (_node *SubscriptionPhase, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionphase.Table, subscriptionphase.Columns, sqlgraph.NewFieldSpec(subscriptionphase.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SubscriptionPhase.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionphase.FieldID)
		for _, f := range fields {
			if !subscriptionphase.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscriptionphase.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscriptionphase.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionphase.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(subscriptionphase.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(subscriptionphase.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(subscriptionphase.FieldUpdatedBy, field.TypeString)
	}
	if _u.mutation.EnvironmentIDCleared() {
		_spec.ClearField(subscriptionphase.FieldEnvironmentID, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(subscriptionphase.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(subscriptionphase.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(subscriptionphase.FieldEndDate, field.TypeTime, value)
	}
	if _u.mutation.EndDateCleared() {
		_spec.ClearField(subscriptionphase.FieldEndDate, field.TypeTime)
	}
	if _u.mutation.SubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionphase.SubscriptionTable,
			Columns: []string{subscriptionphase.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionphase.SubscriptionTable,
			Columns: []string{subscriptionphase.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SubscriptionPhase{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionphase.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
