// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/subscription"
	"github.com/flexprice/flexprice/ent/subscriptionphase"
)

// SubscriptionPhaseCreate is the builder for creating a SubscriptionPhase entity.
type SubscriptionPhaseCreate struct {
	config
	mutation *SubscriptionPhaseMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *SubscriptionPhaseCreate) SetTenantID(v string) *SubscriptionPhaseCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *SubscriptionPhaseCreate) SetStatus(v string) *SubscriptionPhaseCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SubscriptionPhaseCreate) SetNillableStatus(v *string) *SubscriptionPhaseCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SubscriptionPhaseCreate) SetCreatedAt(v time.Time) *SubscriptionPhaseCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SubscriptionPhaseCreate) SetNillableCreatedAt(v *time.Time) *SubscriptionPhaseCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SubscriptionPhaseCreate) SetUpdatedAt(v time.Time) *SubscriptionPhaseCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SubscriptionPhaseCreate) SetNillableUpdatedAt(v *time.Time) *SubscriptionPhaseCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *SubscriptionPhaseCreate) SetCreatedBy(v string) *SubscriptionPhaseCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *SubscriptionPhaseCreate) SetNillableCreatedBy(v *string) *SubscriptionPhaseCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *SubscriptionPhaseCreate) SetUpdatedBy(v string) *SubscriptionPhaseCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *SubscriptionPhaseCreate) SetNillableUpdatedBy(v *string) *SubscriptionPhaseCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetEnvironmentID sets the "environment_id" field.
func (_c *SubscriptionPhaseCreate) SetEnvironmentID(v string) *SubscriptionPhaseCreate {
	_c.mutation.SetEnvironmentID(v)
	return _c
}

// SetNillableEnvironmentID sets the "environment_id" field if the given value is not nil.
func (_c *SubscriptionPhaseCreate) SetNillableEnvironmentID(v *string) *SubscriptionPhaseCreate {
	if v != nil {
		_c.SetEnvironmentID(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *SubscriptionPhaseCreate) SetMetadata(v map[string]string) *SubscriptionPhaseCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetSubscriptionID sets the "subscription_id" field.
func (_c *SubscriptionPhaseCreate) SetSubscriptionID(v string) *SubscriptionPhaseCreate {
	_c.mutation.SetSubscriptionID(v)
	return _c
}

// SetStartDate sets the "start_date" field.
func (_c *SubscriptionPhaseCreate) SetStartDate(v time.Time) *SubscriptionPhaseCreate {
	_c.mutation.SetStartDate(v)
	return _c
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_c *SubscriptionPhaseCreate) SetNillableStartDate(v *time.Time) *SubscriptionPhaseCreate {
	if v != nil {
		_c.SetStartDate(*v)
	}
	return _c
}

// SetEndDate sets the "end_date" field.
func (_c *SubscriptionPhaseCreate) SetEndDate(v time.Time) *SubscriptionPhaseCreate {
	_c.mutation.SetEndDate(v)
	return _c
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_c *SubscriptionPhaseCreate) SetNillableEndDate(v *time.Time) *SubscriptionPhaseCreate {
	if v != nil {
		_c.SetEndDate(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SubscriptionPhaseCreate) SetID(v string) *SubscriptionPhaseCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetSubscription sets the "subscription" edge to the Subscription entity.
func (_c *SubscriptionPhaseCreate) SetSubscription(v *Subscription) *SubscriptionPhaseCreate {
	return _c.SetSubscriptionID(v.ID)
}

// Mutation returns the SubscriptionPhaseMutation object of the builder.
func (_c *SubscriptionPhaseCreate) Mutation() *SubscriptionPhaseMutation {
	return _c.mutation
}

// Save creates the SubscriptionPhase in the database.
func (_c *SubscriptionPhaseCreate) Save(ctx context.Context) (*SubscriptionPhase, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubscriptionPhaseCreate) SaveX(ctx context.Context) *SubscriptionPhase {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionPhaseCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionPhaseCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SubscriptionPhaseCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := subscriptionphase.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := subscriptionphase.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := subscriptionphase.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.EnvironmentID(); !ok {
		v := subscriptionphase.DefaultEnvironmentID
		_c.mutation.SetEnvironmentID(v)
	}
	if _, ok := _c.mutation.StartDate(); !ok {
		v := subscriptionphase.DefaultStartDate()
		_c.mutation.SetStartDate(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubscriptionPhaseCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "SubscriptionPhase.tenant_id"`)}
	}
	if v, ok := _c.mutation.TenantID(); ok {
		if err := subscriptionphase.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPhase.tenant_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SubscriptionPhase.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SubscriptionPhase.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SubscriptionPhase.updated_at"`)}
	}
	if _, ok := _c.mutation.SubscriptionID(); !ok {
		return &ValidationError{Name: "subscription_id", err: errors.New(`ent: missing required field "SubscriptionPhase.subscription_id"`)}
	}
	if v, ok := _c.mutation.SubscriptionID(); ok {
		if err := subscriptionphase.SubscriptionIDValidator(v); err != nil {
			return &ValidationError{Name: "subscription_id", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPhase.subscription_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StartDate(); !ok {
		return &ValidationError{Name: "start_date", err: errors.New(`ent: missing required field "SubscriptionPhase.start_date"`)}
	}
	if len(_c.mutation.SubscriptionIDs()) == 0 {
		return &ValidationError{Name: "subscription", err: errors.New(`ent: missing required edge "SubscriptionPhase.subscription"`)}
	}
	return nil
}

func (_c *SubscriptionPhaseCreate) sqlSave(ctx context.Context) (*SubscriptionPhase, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected SubscriptionPhase.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SubscriptionPhaseCreate) createSpec() (*SubscriptionPhase, *sqlgraph.CreateSpec) {
	var (
		_node = &SubscriptionPhase{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(subscriptionphase.Table, sqlgraph.NewFieldSpec(subscriptionphase.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(subscriptionphase.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(subscriptionphase.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(subscriptionphase.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionphase.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(subscriptionphase.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(subscriptionphase.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	if value, ok := _c.mutation.EnvironmentID(); ok {
		_spec.SetField(subscriptionphase.FieldEnvironmentID, field.TypeString, value)
		_node.EnvironmentID = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(subscriptionphase.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.StartDate(); ok {
		_spec.SetField(subscriptionphase.FieldStartDate, field.TypeTime, value)
		_node.StartDate = value
	}
	if value, ok := _c.mutation.EndDate(); ok {
		_spec.SetField(subscriptionphase.FieldEndDate, field.TypeTime, value)
		_node.EndDate = &value
	}
	if nodes := _c.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionphase.SubscriptionTable,
			Columns: []string{subscriptionphase.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SubscriptionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SubscriptionPhaseCreateBulk is the builder for creating many SubscriptionPhase entities in bulk.
type SubscriptionPhaseCreateBulk struct {
	config
	err      error
	builders []*SubscriptionPhaseCreate
}

// Save creates the SubscriptionPhase entities in the database.
func (_c *SubscriptionPhaseCreateBulk) Save(ctx context.Context) ([]*SubscriptionPhase, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SubscriptionPhase, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubscriptionPhaseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubscriptionPhaseCreateBulk) SaveX(ctx context.Context) []*SubscriptionPhase {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionPhaseCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionPhaseCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
