// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/predicate"
	"github.com/flexprice/flexprice/ent/taxassociation"
	"github.com/flexprice/flexprice/internal/types"
)

// TaxAssociationUpdate is the builder for updating TaxAssociation entities.
type TaxAssociationUpdate struct {
	config
	hooks    []Hook
	mutation *TaxAssociationMutation
}

// Where appends a list predicates to the TaxAssociationUpdate builder.
func (_u *TaxAssociationUpdate) Where(ps ...predicate.TaxAssociation) *TaxAssociationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *TaxAssociationUpdate) SetStatus(v string) *TaxAssociationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TaxAssociationUpdate) SetNillableStatus(v *string) *TaxAssociationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TaxAssociationUpdate) SetUpdatedAt(v time.Time) *TaxAssociationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *TaxAssociationUpdate) SetUpdatedBy(v string) *TaxAssociationUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *TaxAssociationUpdate) SetNillableUpdatedBy(v *string) *TaxAssociationUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *TaxAssociationUpdate) ClearUpdatedBy() *TaxAssociationUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *TaxAssociationUpdate) SetEntityID(v string) *TaxAssociationUpdate {
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *TaxAssociationUpdate) SetNillableEntityID(v *string) *TaxAssociationUpdate {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *TaxAssociationUpdate) SetPriority(v int) *TaxAssociationUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *TaxAssociationUpdate) SetNillablePriority(v *int) *TaxAssociationUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *TaxAssociationUpdate) AddPriority(v int) *TaxAssociationUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetAutoApply sets the "auto_apply" field.
func (_u *TaxAssociationUpdate) SetAutoApply(v bool) *TaxAssociationUpdate {
	_u.mutation.SetAutoApply(v)
	return _u
}

// SetNillableAutoApply sets the "auto_apply" field if the given value is not nil.
func (_u *TaxAssociationUpdate) SetNillableAutoApply(v *bool) *TaxAssociationUpdate {
	if v != nil {
		_u.SetAutoApply(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *TaxAssociationUpdate) SetMetadata(v map[string]string) *TaxAssociationUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *TaxAssociationUpdate) ClearMetadata() *TaxAssociationUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *TaxAssociationUpdate) SetStartDate(v time.Time) *TaxAssociationUpdate {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *TaxAssociationUpdate) SetNillableStartDate(v *time.Time) *TaxAssociationUpdate {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// ClearStartDate clears the value of the "start_date" field.
func (_u *TaxAssociationUpdate) ClearStartDate() *TaxAssociationUpdate {
	_u.mutation.ClearStartDate()
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *TaxAssociationUpdate) SetEndDate(v time.Time) *TaxAssociationUpdate {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *TaxAssociationUpdate) SetNillableEndDate(v *time.Time) *TaxAssociationUpdate {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// ClearEndDate clears the value of the "end_date" field.
func (_u *TaxAssociationUpdate) ClearEndDate() *TaxAssociationUpdate {
	_u.mutation.ClearEndDate()
	return _u
}

// SetTaxBehavior sets the "tax_behavior" field.
func (_u *TaxAssociationUpdate) SetTaxBehavior(v types.TaxBehavior) *TaxAssociationUpdate {
	_u.mutation.SetTaxBehavior(v)
	return _u
}

// SetNillableTaxBehavior sets the "tax_behavior" field if the given value is not nil.
func (_u *TaxAssociationUpdate) SetNillableTaxBehavior(v *types.TaxBehavior) *TaxAssociationUpdate {
	if v != nil {
		_u.SetTaxBehavior(*v)
	}
	return _u
}

// ClearTaxBehavior clears the value of the "tax_behavior" field.
func (_u *TaxAssociationUpdate) ClearTaxBehavior() *TaxAssociationUpdate {
	_u.mutation.ClearTaxBehavior()
	return _u
}

// Mutation returns the TaxAssociationMutation object of the builder.
func (_u *TaxAssociationUpdate) Mutation() *TaxAssociationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TaxAssociationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaxAssociationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TaxAssociationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaxAssociationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TaxAssociationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := taxassociation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaxAssociationUpdate) check() error {
	if v, ok := _u.mutation.EntityID(); ok {
		if err := taxassociation.EntityIDValidator(v); err != nil {
			return &ValidationError{Name: "entity_id", err: fmt.Errorf(`ent: validator failed for field "TaxAssociation.entity_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaxBehavior(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "tax_behavior", err: fmt.Errorf(`ent: validator failed for field "TaxAssociation.tax_behavior": %w`, err)}
		}
	}
	return nil
}

func (_u *TaxAssociationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(taxassociation.Table, taxassociation.Columns, sqlgraph.NewFieldSpec(taxassociation.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(taxassociation.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(taxassociation.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(taxassociation.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(taxassociation.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(taxassociation.FieldUpdatedBy, field.TypeString)
	}
	if _u.mutation.EnvironmentIDCleared() {
		_spec.ClearField(taxassociation.FieldEnvironmentID, field.TypeString)
	}
	if value, ok := _u.mutation.EntityID(); ok {
		_spec.SetField(taxassociation.FieldEntityID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(taxassociation.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(taxassociation.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AutoApply(); ok {
		_spec.SetField(taxassociation.FieldAutoApply, field.TypeBool, value)
	}
	if _u.mutation.CurrencyCleared() {
		_spec.ClearField(taxassociation.FieldCurrency, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(taxassociation.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(taxassociation.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(taxassociation.FieldStartDate, field.TypeTime, value)
	}
	if _u.mutation.StartDateCleared() {
		_spec.ClearField(taxassociation.FieldStartDate, field.TypeTime)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(taxassociation.FieldEndDate, field.TypeTime, value)
	}
	if _u.mutation.EndDateCleared() {
		_spec.ClearField(taxassociation.FieldEndDate, field.TypeTime)
	}
	if value, ok := _u.mutation.TaxBehavior(); ok {
		_spec.SetField(taxassociation.FieldTaxBehavior, field.TypeString, value)
	}
	if _u.mutation.TaxBehaviorCleared() {
		_spec.ClearField(taxassociation.FieldTaxBehavior, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{taxassociation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TaxAssociationUpdateOne is the builder for updating a single TaxAssociation entity.
type TaxAssociationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TaxAssociationMutation
}

// SetStatus sets the "status" field.
func (_u *TaxAssociationUpdateOne) SetStatus(v string) *TaxAssociationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TaxAssociationUpdateOne) SetNillableStatus(v *string) *TaxAssociationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TaxAssociationUpdateOne) SetUpdatedAt(v time.Time) *TaxAssociationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *TaxAssociationUpdateOne) SetUpdatedBy(v string) *TaxAssociationUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *TaxAssociationUpdateOne) SetNillableUpdatedBy(v *string) *TaxAssociationUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *TaxAssociationUpdateOne) ClearUpdatedBy() *TaxAssociationUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *TaxAssociationUpdateOne) SetEntityID(v string) *TaxAssociationUpdateOne {
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *TaxAssociationUpdateOne) SetNillableEntityID(v *string) *TaxAssociationUpdateOne {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *TaxAssociationUpdateOne) SetPriority(v int) *TaxAssociationUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *TaxAssociationUpdateOne) SetNillablePriority(v *int) *TaxAssociationUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *TaxAssociationUpdateOne) AddPriority(v int) *TaxAssociationUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetAutoApply sets the "auto_apply" field.
func (_u *TaxAssociationUpdateOne) SetAutoApply(v bool) *TaxAssociationUpdateOne {
	_u.mutation.SetAutoApply(v)
	return _u
}

// SetNillableAutoApply sets the "auto_apply" field if the given value is not nil.
func (_u *TaxAssociationUpdateOne) SetNillableAutoApply(v *bool) *TaxAssociationUpdateOne {
	if v != nil {
		_u.SetAutoApply(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *TaxAssociationUpdateOne) SetMetadata(v map[string]string) *TaxAssociationUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *TaxAssociationUpdateOne) ClearMetadata() *TaxAssociationUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *TaxAssociationUpdateOne) SetStartDate(v time.Time) *TaxAssociationUpdateOne {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *TaxAssociationUpdateOne) SetNillableStartDate(v *time.Time) *TaxAssociationUpdateOne {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// ClearStartDate clears the value of the "start_date" field.
func (_u *TaxAssociationUpdateOne) ClearStartDate() *TaxAssociationUpdateOne {
	_u.mutation.ClearStartDate()
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *TaxAssociationUpdateOne) SetEndDate(v time.Time) *TaxAssociationUpdateOne {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *TaxAssociationUpdateOne) SetNillableEndDate(v *time.Time) *TaxAssociationUpdateOne {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// ClearEndDate clears the value of the "end_date" field.
func (_u *TaxAssociationUpdateOne) ClearEndDate() *TaxAssociationUpdateOne {
	_u.mutation.ClearEndDate()
	return _u
}

// SetTaxBehavior sets the "tax_behavior" field.
func (_u *TaxAssociationUpdateOne) SetTaxBehavior(v types.TaxBehavior) *TaxAssociationUpdateOne {
	_u.mutation.SetTaxBehavior(v)
	return _u
}

// SetNillableTaxBehavior sets the "tax_behavior" field if the given value is not nil.
func (_u *TaxAssociationUpdateOne) SetNillableTaxBehavior(v *types.TaxBehavior) *TaxAssociationUpdateOne {
	if v != nil {
		_u.SetTaxBehavior(*v)
	}
	return _u
}

// ClearTaxBehavior clears the value of the "tax_behavior" field.
func (_u *TaxAssociationUpdateOne) ClearTaxBehavior() *TaxAssociationUpdateOne {
	_u.mutation.ClearTaxBehavior()
	return _u
}

// Mutation returns the TaxAssociationMutation object of the builder.
func (_u *TaxAssociationUpdateOne) Mutation() *TaxAssociationMutation {
	return _u.mutation
}

// Where appends a list predicates to the TaxAssociationUpdate builder.
func (_u *TaxAssociationUpdateOne) Where(ps ...predicate.TaxAssociation) *TaxAssociationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TaxAssociationUpdateOne) Select(field string, fields ...string) *TaxAssociationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TaxAssociation entity.
func (_u *TaxAssociationUpdateOne) Save(ctx context.Context) (*TaxAssociation, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaxAssociationUpdateOne) SaveX(ctx context.Context) *TaxAssociation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TaxAssociationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaxAssociationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TaxAssociationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := taxassociation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaxAssociationUpdateOne) check() error {
	if v, ok := _u.mutation.EntityID(); ok {
		if err := taxassociation.EntityIDValidator(v); err != nil {
			return &ValidationError{Name: "entity_id", err: fmt.Errorf(`ent: validator failed for field "TaxAssociation.entity_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaxBehavior(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "tax_behavior", err: fmt.Errorf(`ent: validator failed for field "TaxAssociation.tax_behavior": %w`, err)}
		}
	}
	return nil
}

func (_u *TaxAssociationUpdateOne) sqlSave(ctx context.Context) (_node *TaxAssociation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(taxassociation.Table, taxassociation.Columns, sqlgraph.NewFieldSpec(taxassociation.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TaxAssociation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, taxassociation.FieldID)
		for _, f := range fields {
			if !taxassociation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != taxassociation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(taxassociation.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(taxassociation.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(taxassociation.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(taxassociation.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(taxassociation.FieldUpdatedBy, field.TypeString)
	}
	if _u.mutation.EnvironmentIDCleared() {
		_spec.ClearField(taxassociation.FieldEnvironmentID, field.TypeString)
	}
	if value, ok := _u.mutation.EntityID(); ok {
		_spec.SetField(taxassociation.FieldEntityID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(taxassociation.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(taxassociation.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AutoApply(); ok {
		_spec.SetField(taxassociation.FieldAutoApply, field.TypeBool, value)
	}
	if _u.mutation.CurrencyCleared() {
		_spec.ClearField(taxassociation.FieldCurrency, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(taxassociation.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(taxassociation.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(taxassociation.FieldStartDate, field.TypeTime, value)
	}
	if _u.mutation.StartDateCleared() {
		_spec.ClearField(taxassociation.FieldStartDate, field.TypeTime)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(taxassociation.FieldEndDate, field.TypeTime, value)
	}
	if _u.mutation.EndDateCleared() {
		_spec.ClearField(taxassociation.FieldEndDate, field.TypeTime)
	}
	if value, ok := _u.mutation.TaxBehavior(); ok {
		_spec.SetField(taxassociation.FieldTaxBehavior, field.TypeString, value)
	}
	if _u.mutation.TaxBehaviorCleared() {
		_spec.ClearField(taxassociation.FieldTaxBehavior, field.TypeString)
	}
	_node = &TaxAssociation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{taxassociation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
