// Code generated by ent, DO NOT EDIT.

package fxrate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/flexprice/flexprice/ent/predicate"
	"github.com/flexprice/flexprice/internal/types"
	"github.com/shopspring/decimal"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.FXRate {
	return predicate.FXRate(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.FXRate {
	return predicate.FXRate(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.FXRate {
	return predicate.FXRate(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.FXRate {
	return predicate.FXRate(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.FXRate {
	return predicate.FXRate(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.FXRate {
	return predicate.FXRate(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.FXRate {
	return predicate.FXRate(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.FXRate {
	return predicate.FXRate(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.FXRate {
	return predicate.FXRate(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.FXRate {
	return predicate.FXRate(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.FXRate {
	return predicate.FXRate(sql.FieldContainsFold(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldEQ(FieldTenantID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.FXRate {
	return predicate.FXRate(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.FXRate {
	return predicate.FXRate(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldEQ(FieldUpdatedBy, v))
}

// EnvironmentID applies equality check predicate on the "environment_id" field. It's identical to EnvironmentIDEQ.
func EnvironmentID(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldEQ(FieldEnvironmentID, v))
}

// Scope applies equality check predicate on the "scope" field. It's identical to ScopeEQ.
func Scope(v types.FXRateScope) predicate.FXRate {
	vc := string(v)
	return predicate.FXRate(sql.FieldEQ(FieldScope, vc))
}

// ScopeID applies equality check predicate on the "scope_id" field. It's identical to ScopeIDEQ.
func ScopeID(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldEQ(FieldScopeID, v))
}

// FromCurrency applies equality check predicate on the "from_currency" field. It's identical to FromCurrencyEQ.
func FromCurrency(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldEQ(FieldFromCurrency, v))
}

// ToCurrency applies equality check predicate on the "to_currency" field. It's identical to ToCurrencyEQ.
func ToCurrency(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldEQ(FieldToCurrency, v))
}

// Rate applies equality check predicate on the "rate" field. It's identical to RateEQ.
func Rate(v decimal.Decimal) predicate.FXRate {
	return predicate.FXRate(sql.FieldEQ(FieldRate, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v types.FXRateSource) predicate.FXRate {
	vc := string(v)
	return predicate.FXRate(sql.FieldEQ(FieldSource, vc))
}

// StartDate applies equality check predicate on the "start_date" field. It's identical to StartDateEQ.
func StartDate(v time.Time) predicate.FXRate {
	return predicate.FXRate(sql.FieldEQ(FieldStartDate, v))
}

// EndDate applies equality check predicate on the "end_date" field. It's identical to EndDateEQ.
func EndDate(v time.Time) predicate.FXRate {
	return predicate.FXRate(sql.FieldEQ(FieldEndDate, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.FXRate {
	return predicate.FXRate(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.FXRate {
	return predicate.FXRate(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldContainsFold(FieldTenantID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.FXRate {
	return predicate.FXRate(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.FXRate {
	return predicate.FXRate(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.FXRate {
	return predicate.FXRate(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.FXRate {
	return predicate.FXRate(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.FXRate {
	return predicate.FXRate(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.FXRate {
	return predicate.FXRate(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.FXRate {
	return predicate.FXRate(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.FXRate {
	return predicate.FXRate(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.FXRate {
	return predicate.FXRate(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.FXRate {
	return predicate.FXRate(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.FXRate {
	return predicate.FXRate(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.FXRate {
	return predicate.FXRate(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.FXRate {
	return predicate.FXRate(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.FXRate {
	return predicate.FXRate(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.FXRate {
	return predicate.FXRate(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.FXRate {
	return predicate.FXRate(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.FXRate {
	return predicate.FXRate(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.FXRate {
	return predicate.FXRate(sql.FieldLTE(FieldUpdatedAt, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.FXRate {
	return predicate.FXRate(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.FXRate {
	return predicate.FXRate(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.FXRate {
	return predicate.FXRate(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.FXRate {
	return predicate.FXRate(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldContainsFold(FieldCreatedBy, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.FXRate {
	return predicate.FXRate(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.FXRate {
	return predicate.FXRate(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.FXRate {
	return predicate.FXRate(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.FXRate {
	return predicate.FXRate(sql.FieldNotNull(FieldUpdatedBy))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// EnvironmentIDEQ applies the EQ predicate on the "environment_id" field.
func EnvironmentIDEQ(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldEQ(FieldEnvironmentID, v))
}

// EnvironmentIDNEQ applies the NEQ predicate on the "environment_id" field.
func EnvironmentIDNEQ(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldNEQ(FieldEnvironmentID, v))
}

// EnvironmentIDIn applies the In predicate on the "environment_id" field.
func EnvironmentIDIn(vs ...string) predicate.FXRate {
	return predicate.FXRate(sql.FieldIn(FieldEnvironmentID, vs...))
}

// EnvironmentIDNotIn applies the NotIn predicate on the "environment_id" field.
func EnvironmentIDNotIn(vs ...string) predicate.FXRate {
	return predicate.FXRate(sql.FieldNotIn(FieldEnvironmentID, vs...))
}

// EnvironmentIDGT applies the GT predicate on the "environment_id" field.
func EnvironmentIDGT(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldGT(FieldEnvironmentID, v))
}

// EnvironmentIDGTE applies the GTE predicate on the "environment_id" field.
func EnvironmentIDGTE(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldGTE(FieldEnvironmentID, v))
}

// EnvironmentIDLT applies the LT predicate on the "environment_id" field.
func EnvironmentIDLT(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldLT(FieldEnvironmentID, v))
}

// EnvironmentIDLTE applies the LTE predicate on the "environment_id" field.
func EnvironmentIDLTE(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldLTE(FieldEnvironmentID, v))
}

// EnvironmentIDContains applies the Contains predicate on the "environment_id" field.
func EnvironmentIDContains(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldContains(FieldEnvironmentID, v))
}

// EnvironmentIDHasPrefix applies the HasPrefix predicate on the "environment_id" field.
func EnvironmentIDHasPrefix(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldHasPrefix(FieldEnvironmentID, v))
}

// EnvironmentIDHasSuffix applies the HasSuffix predicate on the "environment_id" field.
func EnvironmentIDHasSuffix(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldHasSuffix(FieldEnvironmentID, v))
}

// EnvironmentIDIsNil applies the IsNil predicate on the "environment_id" field.
func EnvironmentIDIsNil() predicate.FXRate {
	return predicate.FXRate(sql.FieldIsNull(FieldEnvironmentID))
}

// EnvironmentIDNotNil applies the NotNil predicate on the "environment_id" field.
func EnvironmentIDNotNil() predicate.FXRate {
	return predicate.FXRate(sql.FieldNotNull(FieldEnvironmentID))
}

// EnvironmentIDEqualFold applies the EqualFold predicate on the "environment_id" field.
func EnvironmentIDEqualFold(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldEqualFold(FieldEnvironmentID, v))
}

// EnvironmentIDContainsFold applies the ContainsFold predicate on the "environment_id" field.
func EnvironmentIDContainsFold(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldContainsFold(FieldEnvironmentID, v))
}

// ScopeEQ applies the EQ predicate on the "scope" field.
func ScopeEQ(v types.FXRateScope) predicate.FXRate {
	vc := string(v)
	return predicate.FXRate(sql.FieldEQ(FieldScope, vc))
}

// ScopeNEQ applies the NEQ predicate on the "scope" field.
func ScopeNEQ(v types.FXRateScope) predicate.FXRate {
	vc := string(v)
	return predicate.FXRate(sql.FieldNEQ(FieldScope, vc))
}

// ScopeIn applies the In predicate on the "scope" field.
func ScopeIn(vs ...types.FXRateScope) predicate.FXRate {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.FXRate(sql.FieldIn(FieldScope, v...))
}

// ScopeNotIn applies the NotIn predicate on the "scope" field.
func ScopeNotIn(vs ...types.FXRateScope) predicate.FXRate {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.FXRate(sql.FieldNotIn(FieldScope, v...))
}

// ScopeGT applies the GT predicate on the "scope" field.
func ScopeGT(v types.FXRateScope) predicate.FXRate {
	vc := string(v)
	return predicate.FXRate(sql.FieldGT(FieldScope, vc))
}

// ScopeGTE applies the GTE predicate on the "scope" field.
func ScopeGTE(v types.FXRateScope) predicate.FXRate {
	vc := string(v)
	return predicate.FXRate(sql.FieldGTE(FieldScope, vc))
}

// ScopeLT applies the LT predicate on the "scope" field.
func ScopeLT(v types.FXRateScope) predicate.FXRate {
	vc := string(v)
	return predicate.FXRate(sql.FieldLT(FieldScope, vc))
}

// ScopeLTE applies the LTE predicate on the "scope" field.
func ScopeLTE(v types.FXRateScope) predicate.FXRate {
	vc := string(v)
	return predicate.FXRate(sql.FieldLTE(FieldScope, vc))
}

// ScopeContains applies the Contains predicate on the "scope" field.
func ScopeContains(v types.FXRateScope) predicate.FXRate {
	vc := string(v)
	return predicate.FXRate(sql.FieldContains(FieldScope, vc))
}

// ScopeHasPrefix applies the HasPrefix predicate on the "scope" field.
func ScopeHasPrefix(v types.FXRateScope) predicate.FXRate {
	vc := string(v)
	return predicate.FXRate(sql.FieldHasPrefix(FieldScope, vc))
}

// ScopeHasSuffix applies the HasSuffix predicate on the "scope" field.
func ScopeHasSuffix(v types.FXRateScope) predicate.FXRate {
	vc := string(v)
	return predicate.FXRate(sql.FieldHasSuffix(FieldScope, vc))
}

// ScopeEqualFold applies the EqualFold predicate on the "scope" field.
func ScopeEqualFold(v types.FXRateScope) predicate.FXRate {
	vc := string(v)
	return predicate.FXRate(sql.FieldEqualFold(FieldScope, vc))
}

// ScopeContainsFold applies the ContainsFold predicate on the "scope" field.
func ScopeContainsFold(v types.FXRateScope) predicate.FXRate {
	vc := string(v)
	return predicate.FXRate(sql.FieldContainsFold(FieldScope, vc))
}

// ScopeIDEQ applies the EQ predicate on the "scope_id" field.
func ScopeIDEQ(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldEQ(FieldScopeID, v))
}

// ScopeIDNEQ applies the NEQ predicate on the "scope_id" field.
func ScopeIDNEQ(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldNEQ(FieldScopeID, v))
}

// ScopeIDIn applies the In predicate on the "scope_id" field.
func ScopeIDIn(vs ...string) predicate.FXRate {
	return predicate.FXRate(sql.FieldIn(FieldScopeID, vs...))
}

// ScopeIDNotIn applies the NotIn predicate on the "scope_id" field.
func ScopeIDNotIn(vs ...string) predicate.FXRate {
	return predicate.FXRate(sql.FieldNotIn(FieldScopeID, vs...))
}

// ScopeIDGT applies the GT predicate on the "scope_id" field.
func ScopeIDGT(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldGT(FieldScopeID, v))
}

// ScopeIDGTE applies the GTE predicate on the "scope_id" field.
func ScopeIDGTE(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldGTE(FieldScopeID, v))
}

// ScopeIDLT applies the LT predicate on the "scope_id" field.
func ScopeIDLT(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldLT(FieldScopeID, v))
}

// ScopeIDLTE applies the LTE predicate on the "scope_id" field.
func ScopeIDLTE(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldLTE(FieldScopeID, v))
}

// ScopeIDContains applies the Contains predicate on the "scope_id" field.
func ScopeIDContains(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldContains(FieldScopeID, v))
}

// ScopeIDHasPrefix applies the HasPrefix predicate on the "scope_id" field.
func ScopeIDHasPrefix(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldHasPrefix(FieldScopeID, v))
}

// ScopeIDHasSuffix applies the HasSuffix predicate on the "scope_id" field.
func ScopeIDHasSuffix(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldHasSuffix(FieldScopeID, v))
}

// ScopeIDEqualFold applies the EqualFold predicate on the "scope_id" field.
func ScopeIDEqualFold(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldEqualFold(FieldScopeID, v))
}

// ScopeIDContainsFold applies the ContainsFold predicate on the "scope_id" field.
func ScopeIDContainsFold(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldContainsFold(FieldScopeID, v))
}

// FromCurrencyEQ applies the EQ predicate on the "from_currency" field.
func FromCurrencyEQ(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldEQ(FieldFromCurrency, v))
}

// FromCurrencyNEQ applies the NEQ predicate on the "from_currency" field.
func FromCurrencyNEQ(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldNEQ(FieldFromCurrency, v))
}

// FromCurrencyIn applies the In predicate on the "from_currency" field.
func FromCurrencyIn(vs ...string) predicate.FXRate {
	return predicate.FXRate(sql.FieldIn(FieldFromCurrency, vs...))
}

// FromCurrencyNotIn applies the NotIn predicate on the "from_currency" field.
func FromCurrencyNotIn(vs ...string) predicate.FXRate {
	return predicate.FXRate(sql.FieldNotIn(FieldFromCurrency, vs...))
}

// FromCurrencyGT applies the GT predicate on the "from_currency" field.
func FromCurrencyGT(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldGT(FieldFromCurrency, v))
}

// FromCurrencyGTE applies the GTE predicate on the "from_currency" field.
func FromCurrencyGTE(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldGTE(FieldFromCurrency, v))
}

// FromCurrencyLT applies the LT predicate on the "from_currency" field.
func FromCurrencyLT(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldLT(FieldFromCurrency, v))
}

// FromCurrencyLTE applies the LTE predicate on the "from_currency" field.
func FromCurrencyLTE(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldLTE(FieldFromCurrency, v))
}

// FromCurrencyContains applies the Contains predicate on the "from_currency" field.
func FromCurrencyContains(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldContains(FieldFromCurrency, v))
}

// FromCurrencyHasPrefix applies the HasPrefix predicate on the "from_currency" field.
func FromCurrencyHasPrefix(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldHasPrefix(FieldFromCurrency, v))
}

// FromCurrencyHasSuffix applies the HasSuffix predicate on the "from_currency" field.
func FromCurrencyHasSuffix(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldHasSuffix(FieldFromCurrency, v))
}

// FromCurrencyEqualFold applies the EqualFold predicate on the "from_currency" field.
func FromCurrencyEqualFold(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldEqualFold(FieldFromCurrency, v))
}

// FromCurrencyContainsFold applies the ContainsFold predicate on the "from_currency" field.
func FromCurrencyContainsFold(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldContainsFold(FieldFromCurrency, v))
}

// ToCurrencyEQ applies the EQ predicate on the "to_currency" field.
func ToCurrencyEQ(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldEQ(FieldToCurrency, v))
}

// ToCurrencyNEQ applies the NEQ predicate on the "to_currency" field.
func ToCurrencyNEQ(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldNEQ(FieldToCurrency, v))
}

// ToCurrencyIn applies the In predicate on the "to_currency" field.
func ToCurrencyIn(vs ...string) predicate.FXRate {
	return predicate.FXRate(sql.FieldIn(FieldToCurrency, vs...))
}

// ToCurrencyNotIn applies the NotIn predicate on the "to_currency" field.
func ToCurrencyNotIn(vs ...string) predicate.FXRate {
	return predicate.FXRate(sql.FieldNotIn(FieldToCurrency, vs...))
}

// ToCurrencyGT applies the GT predicate on the "to_currency" field.
func ToCurrencyGT(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldGT(FieldToCurrency, v))
}

// ToCurrencyGTE applies the GTE predicate on the "to_currency" field.
func ToCurrencyGTE(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldGTE(FieldToCurrency, v))
}

// ToCurrencyLT applies the LT predicate on the "to_currency" field.
func ToCurrencyLT(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldLT(FieldToCurrency, v))
}

// ToCurrencyLTE applies the LTE predicate on the "to_currency" field.
func ToCurrencyLTE(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldLTE(FieldToCurrency, v))
}

// ToCurrencyContains applies the Contains predicate on the "to_currency" field.
func ToCurrencyContains(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldContains(FieldToCurrency, v))
}

// ToCurrencyHasPrefix applies the HasPrefix predicate on the "to_currency" field.
func ToCurrencyHasPrefix(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldHasPrefix(FieldToCurrency, v))
}

// ToCurrencyHasSuffix applies the HasSuffix predicate on the "to_currency" field.
func ToCurrencyHasSuffix(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldHasSuffix(FieldToCurrency, v))
}

// ToCurrencyEqualFold applies the EqualFold predicate on the "to_currency" field.
func ToCurrencyEqualFold(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldEqualFold(FieldToCurrency, v))
}

// ToCurrencyContainsFold applies the ContainsFold predicate on the "to_currency" field.
func ToCurrencyContainsFold(v string) predicate.FXRate {
	return predicate.FXRate(sql.FieldContainsFold(FieldToCurrency, v))
}

// RateEQ applies the EQ predicate on the "rate" field.
func RateEQ(v decimal.Decimal) predicate.FXRate {
	return predicate.FXRate(sql.FieldEQ(FieldRate, v))
}

// RateNEQ applies the NEQ predicate on the "rate" field.
func RateNEQ(v decimal.Decimal) predicate.FXRate {
	return predicate.FXRate(sql.FieldNEQ(FieldRate, v))
}

// RateIn applies the In predicate on the "rate" field.
func RateIn(vs ...decimal.Decimal) predicate.FXRate {
	return predicate.FXRate(sql.FieldIn(FieldRate, vs...))
}

// RateNotIn applies the NotIn predicate on the "rate" field.
func RateNotIn(vs ...decimal.Decimal) predicate.FXRate {
	return predicate.FXRate(sql.FieldNotIn(FieldRate, vs...))
}

// RateGT applies the GT predicate on the "rate" field.
func RateGT(v decimal.Decimal) predicate.FXRate {
	return predicate.FXRate(sql.FieldGT(FieldRate, v))
}

// RateGTE applies the GTE predicate on the "rate" field.
func RateGTE(v decimal.Decimal) predicate.FXRate {
	return predicate.FXRate(sql.FieldGTE(FieldRate, v))
}

// RateLT applies the LT predicate on the "rate" field.
func RateLT(v decimal.Decimal) predicate.FXRate {
	return predicate.FXRate(sql.FieldLT(FieldRate, v))
}

// RateLTE applies the LTE predicate on the "rate" field.
func RateLTE(v decimal.Decimal) predicate.FXRate {
	return predicate.FXRate(sql.FieldLTE(FieldRate, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v types.FXRateSource) predicate.FXRate {
	vc := string(v)
	return predicate.FXRate(sql.FieldEQ(FieldSource, vc))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v types.FXRateSource) predicate.FXRate {
	vc := string(v)
	return predicate.FXRate(sql.FieldNEQ(FieldSource, vc))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...types.FXRateSource) predicate.FXRate {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.FXRate(sql.FieldIn(FieldSource, v...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...types.FXRateSource) predicate.FXRate {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.FXRate(sql.FieldNotIn(FieldSource, v...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v types.FXRateSource) predicate.FXRate {
	vc := string(v)
	return predicate.FXRate(sql.FieldGT(FieldSource, vc))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v types.FXRateSource) predicate.FXRate {
	vc := string(v)
	return predicate.FXRate(sql.FieldGTE(FieldSource, vc))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v types.FXRateSource) predicate.FXRate {
	vc := string(v)
	return predicate.FXRate(sql.FieldLT(FieldSource, vc))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v types.FXRateSource) predicate.FXRate {
	vc := string(v)
	return predicate.FXRate(sql.FieldLTE(FieldSource, vc))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v types.FXRateSource) predicate.FXRate {
	vc := string(v)
	return predicate.FXRate(sql.FieldContains(FieldSource, vc))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v types.FXRateSource) predicate.FXRate {
	vc := string(v)
	return predicate.FXRate(sql.FieldHasPrefix(FieldSource, vc))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v types.FXRateSource) predicate.FXRate {
	vc := string(v)
	return predicate.FXRate(sql.FieldHasSuffix(FieldSource, vc))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v types.FXRateSource) predicate.FXRate {
	vc := string(v)
	return predicate.FXRate(sql.FieldEqualFold(FieldSource, vc))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v types.FXRateSource) predicate.FXRate {
	vc := string(v)
	return predicate.FXRate(sql.FieldContainsFold(FieldSource, vc))
}

// StartDateEQ applies the EQ predicate on the "start_date" field.
func StartDateEQ(v time.Time) predicate.FXRate {
	return predicate.FXRate(sql.FieldEQ(FieldStartDate, v))
}

// StartDateNEQ applies the NEQ predicate on the "start_date" field.
func StartDateNEQ(v time.Time) predicate.FXRate {
	return predicate.FXRate(sql.FieldNEQ(FieldStartDate, v))
}

// StartDateIn applies the In predicate on the "start_date" field.
func StartDateIn(vs ...time.Time) predicate.FXRate {
	return predicate.FXRate(sql.FieldIn(FieldStartDate, vs...))
}

// StartDateNotIn applies the NotIn predicate on the "start_date" field.
func StartDateNotIn(vs ...time.Time) predicate.FXRate {
	return predicate.FXRate(sql.FieldNotIn(FieldStartDate, vs...))
}

// StartDateGT applies the GT predicate on the "start_date" field.
func StartDateGT(v time.Time) predicate.FXRate {
	return predicate.FXRate(sql.FieldGT(FieldStartDate, v))
}

// StartDateGTE applies the GTE predicate on the "start_date" field.
func StartDateGTE(v time.Time) predicate.FXRate {
	return predicate.FXRate(sql.FieldGTE(FieldStartDate, v))
}

// StartDateLT applies the LT predicate on the "start_date" field.
func StartDateLT(v time.Time) predicate.FXRate {
	return predicate.FXRate(sql.FieldLT(FieldStartDate, v))
}

// StartDateLTE applies the LTE predicate on the "start_date" field.
func StartDateLTE(v time.Time) predicate.FXRate {
	return predicate.FXRate(sql.FieldLTE(FieldStartDate, v))
}

// StartDateIsNil applies the IsNil predicate on the "start_date" field.
func StartDateIsNil() predicate.FXRate {
	return predicate.FXRate(sql.FieldIsNull(FieldStartDate))
}

// StartDateNotNil applies the NotNil predicate on the "start_date" field.
func StartDateNotNil() predicate.FXRate {
	return predicate.FXRate(sql.FieldNotNull(FieldStartDate))
}

// EndDateEQ applies the EQ predicate on the "end_date" field.
func EndDateEQ(v time.Time) predicate.FXRate {
	return predicate.FXRate(sql.FieldEQ(FieldEndDate, v))
}

// EndDateNEQ applies the NEQ predicate on the "end_date" field.
func EndDateNEQ(v time.Time) predicate.FXRate {
	return predicate.FXRate(sql.FieldNEQ(FieldEndDate, v))
}

// EndDateIn applies the In predicate on the "end_date" field.
func EndDateIn(vs ...time.Time) predicate.FXRate {
	return predicate.FXRate(sql.FieldIn(FieldEndDate, vs...))
}

// EndDateNotIn applies the NotIn predicate on the "end_date" field.
func EndDateNotIn(vs ...time.Time) predicate.FXRate {
	return predicate.FXRate(sql.FieldNotIn(FieldEndDate, vs...))
}

// EndDateGT applies the GT predicate on the "end_date" field.
func EndDateGT(v time.Time) predicate.FXRate {
	return predicate.FXRate(sql.FieldGT(FieldEndDate, v))
}

// EndDateGTE applies the GTE predicate on the "end_date" field.
func EndDateGTE(v time.Time) predicate.FXRate {
	return predicate.FXRate(sql.FieldGTE(FieldEndDate, v))
}

// EndDateLT applies the LT predicate on the "end_date" field.
func EndDateLT(v time.Time) predicate.FXRate {
	return predicate.FXRate(sql.FieldLT(FieldEndDate, v))
}

// EndDateLTE applies the LTE predicate on the "end_date" field.
func EndDateLTE(v time.Time) predicate.FXRate {
	return predicate.FXRate(sql.FieldLTE(FieldEndDate, v))
}

// EndDateIsNil applies the IsNil predicate on the "end_date" field.
func EndDateIsNil() predicate.FXRate {
	return predicate.FXRate(sql.FieldIsNull(FieldEndDate))
}

// EndDateNotNil applies the NotNil predicate on the "end_date" field.
func EndDateNotNil() predicate.FXRate {
	return predicate.FXRate(sql.FieldNotNull(FieldEndDate))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.FXRate {
	return predicate.FXRate(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.FXRate {
	return predicate.FXRate(sql.FieldNotNull(FieldMetadata))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FXRate) predicate.FXRate {
	return predicate.FXRate(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FXRate) predicate.FXRate {
	return predicate.FXRate(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FXRate) predicate.FXRate {
	return predicate.FXRate(sql.NotPredicates(p))
}
