name: Run Tests

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.12'
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Run Tests
        run: |
          make test

  lint:
    name: Run Loglint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.12'
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Run loglint
        run: make lint-ci
